import type { ModelDefinition, ModelParameter } from "../types";
import {
  AR_GROK,
  AR_IMAGE_BASIC,
  AR_IMAGE_COMMON,
  AR_IMAGE_WIDE,
  PRICES_CHECKED,
  SHAPE_VERIFIED,
  CHECKED_AT,
  FAL_IMAGES_OUTPUT,
  FAL_IMAGE_SIZE,
  KIE_IMAGE_OUTPUT,
  imageRefsSlot,
  omit,
  outputFormatParam,
  qualityParam,
  resolutionParam,
  safetyParam,
  seedParam,
} from "./_shared";

/**
 * Image generation & editing models (MVP scope).
 *
 * Prices are USD list prices seen Aug/Sep 2026. `verified: true` on a pricing
 * block means the fact-check pass of 2026-09-05 confirmed the value against the
 * provider's own page/pricing copy; `verified: false` on a binding means the
 * request schema still has to be checked against the provider's OpenAPI with
 * `pnpm catalog:verify` before relying on it in production.
 *
 * Models with separate text-to-image and edit endpoints keep ONE catalog entry:
 * `endpoint` is the text-to-image endpoint and `endpointByMode.reference` the
 * edit endpoint, selected by `resolveEndpoint()` when reference images are present.
 */

/** OpenAI size boxes accepted by fal's `openai/gpt-image-2` `image_size` field (1K grid: 1024x1024, 1536x1024, 1024x1536). */
const GPT_IMAGE_SIZE_BY_RATIO: Record<string, { width: number; height: number }> = {
  "1:1": { width: 1024, height: 1024 },
  "16:9": { width: 1536, height: 1024 },
  "4:3": { width: 1536, height: 1024 },
  "3:2": { width: 1536, height: 1024 },
  "9:16": { width: 1024, height: 1536 },
  "3:4": { width: 1024, height: 1536 },
  "2:3": { width: 1024, height: 1536 },
};

const gptQualityParam: ModelParameter = {
  name: "quality",
  type: "string",
  required: false,
  description: "OpenAI quality tier (fal only; Kie bills by `resolution`). `high` is the provider default and the expensive tier.",
  default: "high",
  options: ["low", "medium", "high"],
  affects_cost: true,
};

const gptBackgroundParam: ModelParameter = {
  name: "background",
  type: "string",
  required: false,
  description: "Background handling (fal only).",
  options: ["auto", "transparent", "opaque"],
};

const fluxFlexStepsParam: ModelParameter = { name: "num_inference_steps", type: "integer", required: false, description: "Sampling steps (fal FLUX.2 [flex] only).", min: 1, max: 50 };
const fluxFlexGuidanceParam: ModelParameter = { name: "guidance_scale", type: "number", required: false, description: "Guidance scale (fal FLUX.2 [flex] only).", min: 1, max: 20 };

const kontextGuidanceParam: ModelParameter = { name: "guidance_scale", type: "number", required: false, description: "Prompt adherence.", default: 3.5, min: 1, max: 20 };
const kontextSafetyParam: ModelParameter = {
  name: "safety_tolerance",
  type: "string",
  required: false,
  description: "1 (strict) to 6 (permissive); edits allow at most 2.",
  default: "2",
  options: ["1", "2", "3", "4", "5", "6"],
};

const klingElementsParam: ModelParameter = {
  name: "elements",
  type: "object",
  required: false,
  description: "Kling O1 elements: `[{ frontal_image_url, reference_image_urls[] }]` addressed as @Element1..; references + elements <= 10 in total. Passed through untranslated.",
};

const qwenStepsParam: ModelParameter = { name: "num_inference_steps", type: "integer", required: false, description: "Sampling steps.", default: 30, min: 2, max: 50 };
const qwenGuidanceParam: ModelParameter = { name: "guidance_scale", type: "number", required: false, description: "Classifier-free guidance scale.", default: 2.5, min: 0, max: 20 };
const qwenAccelerationParam: ModelParameter = { name: "acceleration", type: "string", required: false, description: "Speed/quality trade-off.", default: "none", options: ["none", "regular", "high"] };

export const IMAGE_MODELS: ModelDefinition[] = [
  {
    id: "nano_banana_pro",
    name: "Nano Banana Pro",
    vendor: "Google",
    description: "Gemini 3 Pro Image: highest quality text rendering, diagrams and photoreal edits with up to 8 reference images. 1K/2K/4K.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [resolutionParam(["1K", "2K", "4K"], "1K", "Output resolution (4K doubles the price on both providers)."), outputFormatParam(["png", "jpeg", "webp"], "png")],
    medias: [imageRefsSlot(8, "Up to 8 reference images (subject, style, product, previous result).")],
    aspect_ratios: [...AR_IMAGE_WIDE],
    max_count: 4,
    tags: ["quality", "text-rendering", "diagrams", "photorealistic", "4k", "editing"],
    higgsfield_ids: ["nano_banana_pro", "nano_banana_2_shots"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/nano-banana-pro",
        endpointByMode: { text: "fal-ai/nano-banana-pro", reference: "fal-ai/nano-banana-pro/edit" },
        priority: 10,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: { field: "num_images", max: 4 },
          roles: { image_references: "image_urls[]" },
          params: { resolution: "resolution", output_format: "output_format" },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: {
          unit: "image",
          usd: 0.15,
          modifiers: [{ when: { resolution: "4K" }, usd: 0.3 }],
          notes: "1K and 2K $0.15 per fal's pricing API (some fal pages list 2K at x1.5 = $0.225); 4K x2; +$0.015 with web search; edit endpoint same price",
          source: "https://fal.ai/models/fal-ai/nano-banana-pro",
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. When image references are present the app switches to fal-ai/nano-banana-pro/edit (endpointByMode.reference).`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "nano-banana-pro",
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: null,
          roles: { image_references: "image_input[]" },
          params: { resolution: "resolution", output_format: { field: "output_format", values: { jpeg: "jpg", png: "png", webp: "png" } } },
          strictParams: true,
        },
        output: KIE_IMAGE_OUTPUT,
        pricing: {
          unit: "image",
          usd: 0.04,
          modifiers: [
            { when: { resolution: "2K" }, usd: 0.09 },
            { when: { resolution: "4K" }, usd: 0.12 },
          ],
          notes: "8 / 18 / 24 credits at 1K / 2K / 4K; an Aug-2026 third-party price pull still showed 18 credits at 1K",
          source: `https://kie.ai/nano-banana-pro (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Same slug for text-to-image and editing (image_input). the verified shape always sends output_format png, so the jpg translation is unverified; aspect_ratio auto is snapped to 1:1 upstream. Doc page lives at docs.kie.ai/market/google/pro-image-to-image.`,
        verified: true,
      },
    ],
  },
  {
    id: "nano_banana_2",
    name: "Nano Banana 2",
    vendor: "Google",
    description: "Gemini 3.1 Flash Image: fast, high-quality generation and editing with up to 14 references; good default for everyday work.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [resolutionParam(["1K", "2K", "4K"], "1K"), outputFormatParam(["png", "jpeg", "webp"], "png")],
    medias: [imageRefsSlot(14, "Up to 14 reference images.")],
    aspect_ratios: [...AR_IMAGE_WIDE],
    max_count: 4,
    tags: ["fast", "high-quality", "photorealistic", "editing", "default"],
    higgsfield_ids: ["nano_banana_2", "nano_banana"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/nano-banana-2",
        endpointByMode: { text: "fal-ai/nano-banana-2", reference: "fal-ai/nano-banana-2/edit" },
        priority: 10,
        input: { aspect_ratio: { field: "aspect_ratio" }, count: { field: "num_images", max: 4 }, roles: { image_references: "image_urls[]" }, params: { resolution: "resolution", output_format: "output_format" }, strictParams: true },
        output: FAL_IMAGES_OUTPUT,
        pricing: {
          unit: "image",
          usd: 0.08,
          modifiers: [{ when: { resolution: "2K" }, usd: 0.12 }, { when: { resolution: "4K" }, usd: 0.16 }],
          notes: "x0.75 at 512px, +$0.015 with web search, +$0.002 high thinking",
          source: "https://fal.ai/models/fal-ai/nano-banana-2",
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Alias fal-ai/gemini-3.1-flash-image-preview. Edits use fal-ai/nano-banana-2/edit.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "nano-banana-2",
        priority: 20,
        input: { aspect_ratio: { field: "aspect_ratio" }, count: null, roles: { image_references: "image_input[]" }, params: { resolution: "resolution", output_format: { field: "output_format", values: { jpeg: "jpg", png: "png", webp: "png" } } }, strictParams: true },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.04, modifiers: [{ when: { resolution: "2K" }, usd: 0.06 }, { when: { resolution: "4K" }, usd: 0.09 }], notes: "8/12/18 credits", source: `https://kie.ai/nano-banana-2 (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Same slug for text-to-image and editing (image_input); the verified shape always sends output_format png, so the jpg translation is unverified.`,
        verified: true,
      },
    ],
  },
  {
    id: "flux_2_pro",
    name: "FLUX.2 [pro]",
    vendor: "Black Forest Labs",
    description: "Precise prompt adherence and multi-reference editing; billed per megapixel on fal.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [resolutionParam(["1K", "2K"], "1K"), seedParam, safetyParam, outputFormatParam(["png", "jpeg"], "png")],
    medias: [imageRefsSlot(8, "Up to 8 reference images for editing / multi-reference generation.")],
    aspect_ratios: [...AR_IMAGE_COMMON],
    max_count: 4,
    tags: ["precise", "prompt-adherence", "editing", "pro"],
    higgsfield_ids: ["flux_2"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/flux-2-pro",
        endpointByMode: { text: "fal-ai/flux-2-pro", reference: "fal-ai/flux-2-pro/edit" },
        priority: 10,
        input: {
          aspect_ratio: FAL_IMAGE_SIZE,
          count: { field: "num_images", max: 4 },
          roles: { image_references: "image_urls[]" },
          params: { resolution: omit("resolution"), seed: "seed", enable_safety_checker: "enable_safety_checker", output_format: "output_format" },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pinnedParams: { resolution: "1K" },
        pricing: { unit: "megapixel", usd: 0.015, first_unit_usd: 0.03, notes: "first MP $0.03, each additional MP $0.015 (input+output)", source: "https://fal.ai/models/fal-ai/flux-2-pro", verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Edits use fal-ai/flux-2-pro/edit with image_urls. image_size is the ~1 MP preset for the ratio; a 2K render would need a {width,height} box that the resolution parameter does not drive, so this binding is pinned to 1K. Outpainting is the separate outpaint catalog model.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "flux-2/pro-text-to-image",
        endpointByMode: { text: "flux-2/pro-text-to-image", reference: "flux-2/pro-image-to-image" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: null,
          roles: { image_references: "input_urls[]" },
          params: { resolution: "resolution", seed: omit("seed"), enable_safety_checker: omit("enable_safety_checker"), output_format: omit("output_format") },
          strictParams: true,
        },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.025, modifiers: [{ when: { resolution: "2K" }, usd: 0.035 }], notes: "5 credits at 1K, 7 at 2K", source: `https://kie.ai/flux-2?model=flux-2%2Fpro-text-to-image (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Body: prompt, aspect_ratio, resolution 1K|2K, plus input_urls (1-8) on flux-2/pro-image-to-image; aspect_ratio auto is accepted on the edit slug only and 21:9 on neither.`,
        verified: true,
      },
    ],
  },
  {
    id: "gpt_image_2",
    name: "GPT Image 2",
    vendor: "OpenAI",
    description: "OpenAI GPT Image 2 (arena codename Hazel): best-in-class text rendering, typography, logos and instruction-following edits with up to 16 references; 1K/2K/4K.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [gptQualityParam, resolutionParam(["1K", "2K", "4K"], "1K", "Output resolution (Kie tiers; on fal the 1K size grid is sent via image_size)."), gptBackgroundParam, outputFormatParam(["png", "jpeg", "webp"], "png")],
    medias: [imageRefsSlot(16, "Up to 16 reference images for edits (fal openai/gpt-image-2/edit, Kie gpt-image-2-image-to-image).")],
    aspect_ratios: [...AR_IMAGE_BASIC],
    aspect_ratio_resolution_limits: { "1:1": ["2K", "1K"] },
    max_count: 4,
    tags: ["text-rendering", "typography", "editing", "logos", "infographic", "4k"],
    higgsfield_ids: ["gpt_image_2", "openai_hazel"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "openai/gpt-image-2",
        endpointByMode: { text: "openai/gpt-image-2", reference: "openai/gpt-image-2/edit" },
        pinnedParams: { resolution: "1K" },
        priority: 10,
        input: {
          aspect_ratio: { size_field: "image_size", sizes: GPT_IMAGE_SIZE_BY_RATIO },
          count: { field: "num_images", max: 4 },
          roles: { image_references: "image_urls[]" },
          params: { quality: "quality", resolution: omit("resolution"), background: "background", output_format: "output_format" },
          byMode: { reference: { aspect_ratio: null, constants: { image_size: "auto" } } },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: {
          unit: "image",
          usd: 0.14,
          modifiers: [
            { when: { quality: "low" }, usd: 0.02 },
            { when: { quality: "medium" }, usd: 0.05 },
          ],
          notes: "token-billed on fal ($8/1M input, $2/1M cached, $30/1M output); budgeted at low $0.02, medium $0.05, high $0.14 per 1K image, references add input tokens",
          source: `https://fal.ai/models/openai/gpt-image-2 (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Owner prefix is openai/. image_size is a {width,height} box on the 1K grid (1024x1024, 1536x1024, 1024x1536) for text-to-image and the string auto on the edit endpoint; 2K/4K only drive Kie. background is passed through when set (outside the verified shape); the edit endpoint also accepts mask_url upstream (not exposed).`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "gpt-image-2-text-to-image",
        endpointByMode: { text: "gpt-image-2-text-to-image", reference: "gpt-image-2-image-to-image" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: null,
          roles: { image_references: "input_urls[]" },
          params: { resolution: "resolution", quality: omit("quality"), background: omit("background"), output_format: omit("output_format") },
          strictParams: true,
        },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.03, modifiers: [{ when: { resolution: "2K" }, usd: 0.05 }, { when: { resolution: "4K" }, usd: 0.08 }], notes: "6/10/16 credits; Kie's own copy also lists a flat 6 credits", source: `https://kie.ai/gpt-image-2 (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. 1:1 is not available at 4K (aspect_ratio_resolution_limits downgrades it to 2K) and 5:4/4:5/3:1/1:3/9:21 only render at 1K (those ratios are not offered here); nsfw_checker defaults to false upstream. Slug spelled gpt-image-2-* in the official catalog (community clients use gpt-image/2-*).`,
        verified: true,
      },
    ],
  },
  {
    id: "gpt_image_2_5_flare",
    name: "GPT Image 2.5 Flare",
    vendor: "OpenAI",
    description: "Kie GPT Image 2.5 Flare for text generation and reference-image editing.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [
      resolutionParam(["1K", "2K", "4K"], "1K"),
      { name: "background", type: "string", required: false, description: "Background mode.", default: "auto", options: ["auto", "transparent", "opaque"] },
    ],
    medias: [imageRefsSlot(16, "Reference images for image-to-image editing. The Kie limit is not yet live-verified.")],
    aspect_ratios: ["auto", "1:1", "3:2", "2:3", "16:9", "9:16", "4:3", "3:4", "21:9", "27:16", "16:27", "9:8", "8:9"],
    aspect_ratio_resolution_limits: { "27:16": ["1K"], "16:27": ["1K"], "9:8": ["1K"], "8:9": ["1K"] },
    max_count: 1,
    tags: ["photoreal", "editing", "text-rendering", "4k"],
    status: "active",
    bindings: [{
      provider: "kie",
      endpoint: "gpt-image-2-5-flare-text-to-image",
      endpointByMode: { reference: "gpt-image-2-5-flare-image-to-image" },
      input: {
        aspect_ratio: { field: "aspect_ratio" },
        count: null,
        roles: { image_references: "input_urls[]" },
        params: { resolution: "resolution", background: "background" },
        strictParams: true,
      },
      output: KIE_IMAGE_OUTPUT,
      pricing: { unit: "image", usd: 0.03, modifiers: [{ when: { resolution: "2K" }, usd: 0.05 }, { when: { resolution: "4K" }, usd: 0.08 }], source: "https://kie.ai/gpt-image-2-5", verified_at: "2026-09-28", verified: true, notes: "Kie public pricing: 6/10/16 credits for 1K/2K/4K. Account charge not yet tested." },
      notes: "Official Kie text and edit slugs documented. Input shape and output pending a live test. Ratios 27:16, 16:27, 9:8 and 8:9 only support 1K.",
      verified: false,
    }],
  },
  {
    id: "gpt_image_2_5_sunburst",
    name: "GPT Image 2.5 Sunburst",
    vendor: "OpenAI",
    description: "Kie GPT Image 2.5 Sunburst for detail-focused text generation and reference-image editing.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [
      resolutionParam(["1K", "2K", "4K"], "1K"),
      { name: "background", type: "string", required: false, description: "Background mode.", default: "auto", options: ["auto", "transparent", "opaque"] },
    ],
    medias: [imageRefsSlot(16, "Reference images for image-to-image editing. The Kie limit is not yet live-verified.")],
    aspect_ratios: ["auto", "1:1", "3:2", "2:3", "16:9", "9:16", "4:3", "3:4", "21:9", "27:16", "16:27", "9:8", "8:9"],
    aspect_ratio_resolution_limits: { "27:16": ["1K"], "16:27": ["1K"], "9:8": ["1K"], "8:9": ["1K"] },
    max_count: 1,
    tags: ["photoreal", "editing", "text-rendering", "4k"],
    status: "active",
    bindings: [{
      provider: "kie",
      endpoint: "gpt-image-2-5-sunburst-text-to-image",
      endpointByMode: { reference: "gpt-image-2-5-sunburst-image-to-image" },
      input: {
        aspect_ratio: { field: "aspect_ratio" },
        count: null,
        roles: { image_references: "input_urls[]" },
        params: { resolution: "resolution", background: "background" },
        strictParams: true,
      },
      output: KIE_IMAGE_OUTPUT,
      pricing: { unit: "image", usd: 0.03, modifiers: [{ when: { resolution: "2K" }, usd: 0.05 }, { when: { resolution: "4K" }, usd: 0.08 }], source: "https://kie.ai/gpt-image-2-5", verified_at: "2026-09-28", verified: true, notes: "Kie public pricing: 6/10/16 credits for 1K/2K/4K. Account charge not yet tested." },
      notes: "Official Kie text and edit slugs documented. Input shape and output pending a live test. Ratios 27:16, 16:27, 9:8 and 8:9 only support 1K.",
      verified: false,
    }],
  },
  {
    id: "soul_standard_api",
    name: "Higgsfield Soul Standard",
    vendor: "Higgsfield",
    description: "Soul Standard image generation through the separate Higgsfield API.",
    output_type: "image",
    capabilities: ["text-to-image"],
    parameters: [
      resolutionParam(["720p", "1080p"], "720p"),
      { name: "batch_size", type: "integer", required: false, description: "Result images, 1 or 4.", default: 1, options: [1, 4], affects_cost: true },
      { name: "seed", type: "integer", required: false, description: "Reproducible seed.", min: 1, max: 1_000_000 },
      { name: "style_id", type: "string", required: false, description: "Higgsfield Soul style ID." },
      { name: "enhance_prompt", type: "boolean", required: false, description: "Enhance the prompt.", default: true },
      { name: "style_strength", type: "number", required: false, description: "Strength of the chosen style.", default: 1, min: 0, max: 1 },
    ],
    medias: [],
    aspect_ratios: ["4:3", "9:16", "16:9", "3:4", "1:1", "2:3", "3:2"],
    max_count: 1,
    tags: ["soul", "photoreal", "portrait"],
    status: "beta",
    bindings: [{
      provider: "higgsfield",
      endpoint: "higgsfield-ai/soul/standard",
      supportedModes: ["text"],
      input: { aspect_ratio: { field: "aspect_ratio" }, count: null, params: { resolution: "resolution", batch_size: "batch_size", seed: "seed", style_id: "style_id", enhance_prompt: "enhance_prompt", style_strength: "style_strength" }, strictParams: true },
      output: { outputs: [{ path: "images[]", kind: "image" }] },
      notes: "Current model-specific Higgsfield API reference (2026-09-28) supersedes its stale public OpenAPI subset. Account-specific USD price comes from /estimate. Live generation pending.",
      verified: false,
    }],
  },
  {
    id: "soul_2_api",
    name: "Higgsfield Soul 2",
    vendor: "Higgsfield",
    description: "Soul 2 standard image generation through the separate Higgsfield API.",
    output_type: "image",
    capabilities: ["text-to-image"],
    parameters: [
      resolutionParam(["720p", "1080p"], "720p"),
      { name: "batch_size", type: "integer", required: false, description: "Result images, 1 or 4.", default: 1, options: [1, 4], affects_cost: true },
      { name: "seed", type: "integer", required: false, description: "Reproducible seed.", min: 1, max: 1_000_000 },
      { name: "style_id", type: "string", required: false, description: "Higgsfield Soul style ID." },
      { name: "enhance_prompt", type: "boolean", required: false, description: "Enhance the prompt.", default: true },
    ],
    medias: [],
    aspect_ratios: ["4:3", "9:16", "16:9", "3:4", "1:1", "2:3", "3:2"],
    max_count: 1,
    tags: ["soul", "photoreal", "portrait"],
    higgsfield_ids: ["soul_2"],
    status: "beta",
    bindings: [{
      provider: "higgsfield",
      endpoint: "higgsfield-ai/soul/v2/standard",
      supportedModes: ["text"],
      input: { aspect_ratio: { field: "aspect_ratio" }, count: null, params: { resolution: "resolution", batch_size: "batch_size", seed: "seed", style_id: "style_id", enhance_prompt: "enhance_prompt" }, strictParams: true },
      output: { outputs: [{ path: "images[]", kind: "image" }] },
      notes: "Current model-specific Higgsfield API reference lists 720p/1080p, aspect ratio, batch size, seed and style. Single-image text generation succeeded live; account quote may exceed final charge.",
      verified: false,
    }],
  },
  {
    id: "seedream_v5_pro",
    name: "Seedream 5.0 Pro",
    vendor: "ByteDance",
    description: "Seedream 5.0 Pro: instruction-following generation and editing with reasoning, up to 2K; strong on product and character consistency.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [qualityParam(["basic", "high"], "basic", "Output size on Kie: basic = 1K/1.5K, high = 2K (fal sizes come from image_size)."), outputFormatParam(["png", "jpeg"], "png"), safetyParam],
    medias: [imageRefsSlot(10, "Up to 10 reference images for editing (Kie: +$0.0025 per input image after the first).")],
    aspect_ratios: [...AR_IMAGE_COMMON, "21:9"],
    max_count: 4,
    tags: ["editing", "instruction", "reasoning", "pro", "2k", "consistency"],
    higgsfield_ids: ["seedream_v5_pro"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "bytedance/seedream/v5/pro/text-to-image",
        endpointByMode: { text: "bytedance/seedream/v5/pro/text-to-image", reference: "bytedance/seedream/v5/pro/edit" },
        pinnedParams: { quality: "basic" },
        priority: 10,
        input: {
          aspect_ratio: FAL_IMAGE_SIZE,
          count: { field: "num_images", max: 4 },
          roles: { image_references: "image_urls[]" },
          params: { quality: omit("quality"), output_format: "output_format", enable_safety_checker: "enable_safety_checker" },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: {
          unit: "image",
          usd: 0.0675,
          notes: "$0.0675 per image below 1536^2 (the ~1 MP presets sent here), $0.135 above (image_size auto_2K selects the 2K tier, not encoded here); edit +$0.0045 per extra input image; a third-party probe (2026-08-28) was billed $0.135 for 1024^2 - watch the first invoices",
          source: `https://fal.ai/models/bytedance/seedream/v5/pro/text-to-image (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. The v5 ids carry NO fal-ai/ prefix in the Sep-2026 registry (v4/v4.5 keep it). quality is Kie-only here (fal's 2K tier is image_size auto_2K, which the size map cannot express), so this binding is pinned to basic. Layer decomposition: bytedance/seedream/v5/pro/layerize (compute-second billed).`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "seedream/5-pro-text-to-image",
        endpointByMode: { text: "seedream/5-pro-text-to-image", reference: "seedream/5-pro-image-to-image" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: null,
          roles: { image_references: "image_urls[]" },
          params: { quality: "quality", output_format: "output_format", enable_safety_checker: omit("enable_safety_checker") },
          strictParams: true,
        },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.035, modifiers: [{ when: { quality: "high" }, usd: 0.07 }], notes: "7 credits (1K/1.5K) / 14 credits (2K); +0.5 credit per input image after the first", source: `https://kie.ai/seedream-5-0-pro (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Body: prompt, aspect_ratio, quality basic|high, output_format png, plus image_urls on seedream/5-pro-image-to-image. Layer decomposition: seedream/5-pro-layer-decomposition (billed per output layer).`,
        verified: true,
      },
    ],
  },
  {
    id: "seedream_v5_lite",
    name: "Seedream 5.0 Lite",
    vendor: "ByteDance",
    description: "Seedream 5.0 Lite: the smart budget editor - instruction-following edits and generation up to ~3K at a flat per-image price.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [qualityParam(["basic", "high", "ultra"], "basic", "Kie quality tier (basic = 1K, high = 2K, ultra = 4K; all priced alike); fal sizes come from image_size."), outputFormatParam(["png", "jpeg"], "png"), safetyParam],
    medias: [imageRefsSlot(10, "Up to 10 reference images for editing.")],
    aspect_ratios: [...AR_IMAGE_COMMON, "21:9"],
    max_count: 4,
    tags: ["editing", "instruction", "budget", "versatile", "smart"],
    higgsfield_ids: ["seedream_v5_lite"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "bytedance/seedream/v5/lite/text-to-image",
        endpointByMode: { text: "bytedance/seedream/v5/lite/text-to-image", reference: "bytedance/seedream/v5/lite/edit" },
        pinnedParams: { quality: "basic" },
        priority: 10,
        input: {
          aspect_ratio: FAL_IMAGE_SIZE,
          count: { field: "num_images", max: 4 },
          roles: { image_references: "image_urls[]" },
          params: { quality: omit("quality"), output_format: "output_format", enable_safety_checker: "enable_safety_checker" },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: { unit: "image", usd: 0.035, notes: "flat, up to ~9 MP", source: "https://fal.ai/models/bytedance/seedream/v5/lite/text-to-image", verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Registry id has no fal-ai/ prefix; the prefixed form fal-ai/bytedance/seedream/v5/lite/* worked in July 2026 and may still be aliased. quality is Kie-only here (fal's 2K/4K tiers are image_size auto_2K/auto_4K, which the size map cannot express), so this binding is pinned to basic.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "seedream/5-lite-text-to-image",
        endpointByMode: { text: "seedream/5-lite-text-to-image", reference: "seedream/5-lite-image-to-image" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: null,
          roles: { image_references: "image_urls[]" },
          params: { quality: "quality", output_format: "output_format", enable_safety_checker: omit("enable_safety_checker") },
          strictParams: true,
        },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.0275, notes: "5.5 credits for basic, high and ultra alike (docs mirror says 5)", source: `https://kie.ai/seedream-5-0-lite (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Body: prompt, aspect_ratio, quality basic|high|ultra, output_format png, plus image_urls on seedream/5-lite-image-to-image.`,
        verified: true,
      },
    ],
  },
  {
    id: "seedream_v4_5",
    name: "Seedream 4.5",
    vendor: "ByteDance",
    description: "Seedream 4.5: precise transformations and controllable edits up to 4K.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [qualityParam(["basic", "high"], "basic", "Kie output size: basic = 2K, high = 4K (fal sizes come from image_size)."), outputFormatParam(["png", "jpeg"], "png"), safetyParam],
    medias: [imageRefsSlot(10, "Reference images for editing.")],
    aspect_ratios: [...AR_IMAGE_COMMON],
    max_count: 4,
    tags: ["4k", "high-resolution", "precise", "transformations", "editing", "control"],
    higgsfield_ids: ["seedream_v4_5"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/bytedance/seedream/v4.5/text-to-image",
        endpointByMode: { text: "fal-ai/bytedance/seedream/v4.5/text-to-image", reference: "fal-ai/bytedance/seedream/v4.5/edit" },
        pinnedParams: { quality: "basic" },
        priority: 10,
        input: {
          aspect_ratio: FAL_IMAGE_SIZE,
          count: { field: "num_images", max: 4 },
          roles: { image_references: "image_urls[]" },
          params: { quality: omit("quality"), output_format: "output_format", enable_safety_checker: "enable_safety_checker" },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: { unit: "image", usd: 0.04, source: "https://fal.ai/models/fal-ai/bytedance/seedream/v4.5/edit", verified_at: CHECKED_AT, verified: true },
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "seedream/4.5-text-to-image",
        endpointByMode: { text: "seedream/4.5-text-to-image", reference: "seedream/4.5-edit" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: null,
          roles: { image_references: "image_urls[]" },
          params: { quality: "quality", output_format: omit("output_format"), enable_safety_checker: omit("enable_safety_checker") },
          strictParams: true,
        },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.0325, notes: "6.5 credits per Kie's own copy (docs mirror says 5)", source: "https://kie.ai/seedream-4-5", verified_at: CHECKED_AT, verified: false },
        verified: false,
      },
    ],
  },
  {
    id: "flux_2_flex",
    name: "FLUX.2 [flex]",
    vendor: "Black Forest Labs",
    description: "FLUX.2 [flex]: the tunable FLUX.2 tier (steps / guidance exposed) for typography-heavy and controllable work; billed per megapixel on fal.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [resolutionParam(["1K", "2K"], "1K"), fluxFlexStepsParam, fluxFlexGuidanceParam, seedParam, safetyParam, outputFormatParam(["png", "jpeg"], "png")],
    medias: [imageRefsSlot(8, "Up to 8 reference images for editing / multi-reference generation.")],
    aspect_ratios: [...AR_IMAGE_COMMON, "21:9"],
    max_count: 4,
    tags: ["controllable", "typography", "flex", "steps"],
    higgsfield_ids: ["flux_2"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/flux-2-flex",
        endpointByMode: { text: "fal-ai/flux-2-flex", reference: "fal-ai/flux-2-flex/edit" },
        pinnedParams: { resolution: "1K" },
        priority: 10,
        input: {
          aspect_ratio: FAL_IMAGE_SIZE,
          count: { field: "num_images", max: 4 },
          roles: { image_references: "image_urls[]" },
          params: {
            resolution: omit("resolution"),
            num_inference_steps: "num_inference_steps",
            guidance_scale: "guidance_scale",
            seed: "seed",
            enable_safety_checker: "enable_safety_checker",
            output_format: "output_format",
          },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: { unit: "megapixel", usd: 0.05, notes: "input+output megapixels; one fal page lists $0.06/MP - re-check via the pricing API", source: "https://fal.ai/models/fal-ai/flux-2-flex", verified_at: CHECKED_AT, verified: false },
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "flux-2/flex-text-to-image",
        endpointByMode: { text: "flux-2/flex-text-to-image", reference: "flux-2/flex-image-to-image" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: null,
          roles: { image_references: "input_urls[]" },
          params: {
            resolution: "resolution",
            num_inference_steps: omit("num_inference_steps"),
            guidance_scale: omit("guidance_scale"),
            seed: omit("seed"),
            enable_safety_checker: omit("enable_safety_checker"),
            output_format: omit("output_format"),
          },
          strictParams: true,
        },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.07, modifiers: [{ when: { resolution: "2K" }, usd: 0.12 }], notes: "third-party marketplace pull 2026-08-06 (14/24 credits); a community price tracker lists 4 credits ($0.02) - reconcile with creditsConsumed", source: "https://kie.ai/flux-2?model=flux-2%2Fflex-text-to-image", verified_at: CHECKED_AT, verified: false },
        verified: false,
      },
    ],
  },
  {
    id: "flux_2_max",
    name: "FLUX.2 [max]",
    vendor: "Black Forest Labs",
    description: "FLUX.2 [max]: the highest-fidelity FLUX.2 tier for hero images and demanding edits; billed per megapixel on fal.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [seedParam, safetyParam, outputFormatParam(["png", "jpeg"], "png")],
    medias: [imageRefsSlot(8, "Up to 8 reference images for editing / multi-reference generation.")],
    aspect_ratios: [...AR_IMAGE_COMMON, "21:9"],
    max_count: 4,
    tags: ["quality", "max", "hero", "editing"],
    higgsfield_ids: ["flux_2"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/flux-2-max",
        endpointByMode: { text: "fal-ai/flux-2-max", reference: "fal-ai/flux-2-max/edit" },
        priority: 10,
        input: {
          aspect_ratio: FAL_IMAGE_SIZE,
          count: { field: "num_images", max: 4 },
          roles: { image_references: "image_urls[]" },
          params: { seed: "seed", enable_safety_checker: "enable_safety_checker", output_format: "output_format" },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: { unit: "megapixel", usd: 0.03, first_unit_usd: 0.07, notes: "first MP $0.07, each additional MP $0.03 (text-to-image and edit)", source: "https://fal.ai/models/fal-ai/flux-2-max", verified_at: CHECKED_AT, verified: true },
        notes: "fal only: Kie's catalog has no FLUX.2 [max] (confirmed absent Aug/Sep 2026). Renders the ~1 MP image_size preset for the ratio; there is no resolution choice until a {width,height} box is wired.",
        verified: false,
      },
    ],
  },
  {
    id: "flux_kontext_pro",
    name: "FLUX.1 Kontext [pro]",
    vendor: "Black Forest Labs",
    description: "Context-aware single-image editing, style transfer and remixing (FLUX.1 Kontext pro); text-to-image through the /text-to-image variant.",
    output_type: "image",
    capabilities: ["image-edit", "image-to-image", "text-to-image"],
    parameters: [kontextGuidanceParam, kontextSafetyParam, seedParam, outputFormatParam(["jpeg", "png"], "jpeg")],
    medias: [{ role: "image", kind: "image", description: "Image to edit / restyle (omit for text-to-image)." }],
    aspect_ratios: ["1:1", "16:9", "9:16", "4:3", "3:4", "3:2", "2:3", "21:9", "9:21"],
    max_count: 4,
    tags: ["editing", "style-transfer", "context-aware", "typography", "remix"],
    higgsfield_ids: ["flux_kontext"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/flux-pro/kontext",
        endpointByMode: { text: "fal-ai/flux-pro/kontext/text-to-image", reference: "fal-ai/flux-pro/kontext" },
        priority: 10,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: { field: "num_images", max: 4 },
          roles: { image: "image_url" },
          params: { guidance_scale: "guidance_scale", safety_tolerance: "safety_tolerance", seed: "seed", output_format: "output_format" },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: { unit: "image", usd: 0.04, notes: "max variant fal-ai/flux-pro/kontext/max $0.08", source: "https://fal.ai/models/fal-ai/flux-pro/kontext", verified_at: CHECKED_AT, verified: false },
        notes:
          "fal only for now: Kie hosts flux-kontext-pro/max through its separate /api/v1/flux/kontext/generate family (aspectRatio, inputImage, outputFormat, promptUpsampling, safetyTolerance...) which the Kie adapter does not support yet. Multi-image variant: fal-ai/flux-pro/kontext/multi (image_urls). Largely superseded by FLUX.2 edit.",
        verified: false,
      },
    ],
  },
  {
    id: "kling_image_o1",
    name: "Kling O1 Image",
    vendor: "Kling",
    description: "Kling O1 image: cheap multi-reference compositor - cast up to 10 reference images (@Image1..@Image10) into one scene; 1K/2K, up to 9 variations.",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [resolutionParam(["1K", "2K"], "1K"), outputFormatParam(["png", "jpeg"], "png"), klingElementsParam],
    medias: [imageRefsSlot(10, "Up to 10 reference images, addressed as @Image1..@Image10 in the prompt (<= 2500 chars).")],
    aspect_ratios: [...AR_IMAGE_WIDE],
    max_count: 9,
    tags: ["photorealistic", "multi-reference", "character", "consistent", "wide-aspect-ratio", "budget"],
    higgsfield_ids: ["kling_omni_image"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/kling-image/o1",
        priority: 10,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: { field: "num_images", max: 9 },
          roles: { image_references: "image_urls[]" },
          params: { resolution: "resolution", output_format: "output_format", elements: "elements" },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: { unit: "image", usd: 0.028, source: "https://fal.ai/models/fal-ai/kling-image/o1", verified_at: CHECKED_AT, verified: true },
        notes: "Single endpoint for text-to-image and reference editing. fal only: Kie has no Kling O1 image model (confirmed absent). Siblings: fal-ai/kling-image/o3/*, fal-ai/kling-image/v3/*.",
        verified: false,
      },
    ],
  },
  {
    id: "z_image_turbo",
    name: "Z-Image Turbo",
    vendor: "Tongyi-MAI",
    description: "Z-Image Turbo: the cheapest photoreal generator - fast drafts and stylized quick renders at a fraction of a cent.",
    output_type: "image",
    capabilities: ["text-to-image"],
    parameters: [seedParam, safetyParam, outputFormatParam(["png", "jpeg"], "png")],
    medias: [],
    aspect_ratios: [...AR_IMAGE_BASIC],
    max_count: 4,
    tags: ["fast", "budget", "stylized", "quick", "drafts"],
    higgsfield_ids: ["z_image"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/z-image/turbo",
        priority: 10,
        input: {
          aspect_ratio: FAL_IMAGE_SIZE,
          count: { field: "num_images", max: 4 },
          params: { seed: "seed", enable_safety_checker: "enable_safety_checker", output_format: "output_format" },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: { unit: "megapixel", usd: 0.005, notes: "LoRA variant fal-ai/z-image/turbo/lora $0.0085/MP", source: "https://fal.ai/models/fal-ai/z-image/turbo", verified_at: CHECKED_AT, verified: false },
        notes: `${SHAPE_VERIFIED}. Body: prompt, image_size preset, output_format png. Image-to-image / inpaint / controlnet siblings exist under fal-ai/z-image/turbo/* (not wired).`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "z-image",
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: null,
          params: { seed: omit("seed"), enable_safety_checker: omit("enable_safety_checker"), output_format: omit("output_format") },
          strictParams: true,
        },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.004, notes: "0.8 credit per image (the docs mirror's 3 credits is stale; a third-party 2026-08 pull agrees on $0.004)", source: `https://kie.ai/z-image (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Body is just prompt + aspect_ratio (1:1, 4:3, 3:4, 16:9, 9:16).`,
        verified: true,
      },
    ],
  },
  {
    id: "grok_image_2",
    name: "Grok Imagine Image 2.0",
    vendor: "xAI",
    description: "xAI Grok Imagine Image 2.0: expressive, high-contrast, bold creative renders with multi-reference editing (1K/2K on fal).",
    output_type: "image",
    capabilities: ["text-to-image", "image-to-image", "image-edit"],
    parameters: [resolutionParam(["1K", "2K"], "1K", "Output resolution (fal only; Kie has a single tier).")],
    medias: [imageRefsSlot(3, "Reference images for editing (fal accepts at most 3; Kie up to 5).")],
    aspect_ratios: [...AR_GROK],
    max_count: 4,
    tags: ["expressive", "high-contrast", "editing", "creative", "bold"],
    higgsfield_ids: ["grok_image", "grok_image_2_0"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "xai/grok-imagine-image/v2.0/text-to-image",
        endpointByMode: { text: "xai/grok-imagine-image/v2.0/text-to-image", reference: "xai/grok-imagine-image/v2.0/edit" },
        priority: 10,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: { field: "num_images", max: 4 },
          roles: { image_references: "image_urls[]" },
          params: { resolution: { field: "resolution", values: { "1K": "1k", "2K": "2k" } } },
          constants: { quality: "low", output_format: "png" },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: {
          unit: "image",
          usd: 0.04,
          modifiers: [{ when: { resolution: "2K" }, usd: 0.06 }],
          notes: "quality low: $0.04 (1k) / $0.06 (2k) per image, +$0.01 per reference image; the unversioned xai/grok-imagine-image endpoints bill $0.02/image",
          source: `https://fal.ai/models/xai/grok-imagine-image/v2.0/text-to-image (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Body: prompt, aspect_ratio (auto, 16:9, 4:3, 3:2, 1:1, 2:3, 3:4, 9:16), resolution 1k|2k, quality low, output_format png, plus image_urls (<= 3) on the edit endpoint.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "grok-imagine-image-2-0/text-to-image",
        endpointByMode: { text: "grok-imagine-image-2-0/text-to-image", reference: "grok-imagine-image-2-0/image-edit" },
        pinnedParams: { resolution: "1K" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          count: null,
          roles: { image_references: "image_urls[]" },
          params: { resolution: omit("resolution") },
          strictParams: true,
        },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.02, notes: "4 credits per image", source: `https://kie.ai/grok-imagine (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Body is prompt + aspect_ratio (1:1, 2:3, 3:2, 16:9, 9:16; auto on the edit slug only) plus image_urls on grok-imagine-image-2-0/image-edit. The older grok-imagine/text-to-image slug (4 credits for 6 images) is not wired.`,
        verified: true,
      },
    ],
  },
  {
    id: "qwen_image",
    name: "Qwen-Image",
    vendor: "Alibaba",
    description: "Open-weight Qwen-Image (20B MMDiT): strong multilingual text rendering at a budget megapixel price.",
    output_type: "image",
    capabilities: ["text-to-image"],
    parameters: [qwenStepsParam, qwenGuidanceParam, qwenAccelerationParam, seedParam, safetyParam, outputFormatParam(["png", "jpeg"], "png")],
    medias: [],
    aspect_ratios: [...AR_IMAGE_COMMON],
    max_count: 4,
    tags: ["open-weights", "text-rendering", "multilingual", "budget"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/qwen-image",
        priority: 10,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: FAL_IMAGE_SIZE,
          count: { field: "num_images", max: 4 },
          params: {
            num_inference_steps: "num_inference_steps",
            guidance_scale: "guidance_scale",
            acceleration: "acceleration",
            seed: "seed",
            enable_safety_checker: "enable_safety_checker",
            output_format: "output_format",
          },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: { unit: "megapixel", usd: 0.02, source: "https://fal.ai/models/fal-ai/qwen-image (third-party pricing pull 2026-08)", verified_at: CHECKED_AT, verified: false },
        notes: "Original Qwen-Image; Qwen Image 3 lives at alibaba/qwen-image-3/* (compute-second billed) and is not wired.",
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "qwen/text-to-image",
        priority: 20,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: FAL_IMAGE_SIZE,
          count: null,
          params: {
            num_inference_steps: "num_inference_steps",
            guidance_scale: "guidance_scale",
            acceleration: "acceleration",
            seed: omit("seed"),
            enable_safety_checker: omit("enable_safety_checker"),
            output_format: omit("output_format"),
          },
          strictParams: true,
        },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.02, notes: "4 credits", source: "https://kie.ai/qwen-image", verified_at: CHECKED_AT, verified: false },
        notes: "Kie mirrors fal's schema (image_size presets, num_inference_steps, guidance_scale, acceleration) - verify with a live 422 probe.",
        verified: false,
      },
    ],
  },
];
