import type { ModelDefinition, ModelParameter } from "../types";
import { PRICES_CHECKED, SHAPE_VERIFIED, CHECKED_AT, FAL_IMAGES_OUTPUT, FAL_IMAGE_OUTPUT, FAL_VIDEO_OUTPUT, KIE_IMAGE_OUTPUT, KIE_VIDEO_OUTPUT, omit, outputFormatParam, safetyParam, seedParam, sourceImageSlot, sourceVideoSlot, upscaleFactorParam } from "./_shared";

/**
 * Image and video utilities (upscale, background removal, outpaint, reframe).
 * Utilities take a single required `image` / `video` media, usually have no
 * prompt (`prompt: null` in the input mapping) and ignore aspect ratios
 * (`aspect_ratios: []`) except reframe.
 */

const expandParam = (side: "left" | "right" | "top" | "bottom"): ModelParameter => ({
  name: `expand_${side}`,
  type: "integer",
  required: false,
  description: `Pixels to add on the ${side} side.`,
  default: 0,
  min: 0,
  max: 2048,
});

const clarityCreativityParam: ModelParameter = { name: "creativity", type: "number", required: false, description: "How much the upscaler may hallucinate detail (0 = faithful).", default: 0.35, min: 0, max: 1 };
const clarityResemblanceParam: ModelParameter = { name: "resemblance", type: "number", required: false, description: "How closely to follow the source.", default: 0.6, min: 0, max: 1 };

const targetResolutionParam: ModelParameter = {
  name: "target_resolution",
  type: "string",
  required: false,
  description: "Output resolution tier.",
  default: "1080p",
  options: ["1080p", "2k", "4k"],
  affects_cost: true,
};

const topazVideoFactorParam: ModelParameter = { name: "upscale_factor", type: "integer", required: false, description: "Upscale multiplier.", default: 2, options: [1, 2, 4], affects_cost: true };

const birefnetModelParam: ModelParameter = {
  name: "model",
  type: "string",
  required: false,
  description: "BiRefNet checkpoint (fal only).",
  default: "General Use (Light)",
  options: ["General Use (Light)", "General Use (Heavy)", "Portrait", "Matting"],
};

export const UTILITY_MODELS: ModelDefinition[] = [
  {
    id: "upscale_image_topaz",
    name: "Topaz Image Upscale",
    vendor: "Topaz Labs",
    description: "Topaz precision image upscaling (1x-8x) for print-ready detail.",
    output_type: "image",
    capabilities: ["upscale-image"],
    parameters: [upscaleFactorParam([1, 2, 4, 8], 2)],
    medias: [sourceImageSlot],
    aspect_ratios: [],
    max_count: 1,
    tags: ["upscale", "topaz", "print", "utility"],
    higgsfield_ids: ["topaz_image"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "topaz/upscale/image/precision",
        priority: 10,
        input: { prompt: null, aspect_ratio: null, count: null, roles: { image: "image_url" }, params: { upscale_factor: "upscale_factor" }, strictParams: true },
        output: FAL_IMAGE_OUTPUT,
        pricing: { unit: "generation", usd: 0.08, notes: "$0.08 per started 24 MP of OUTPUT (any precision model); billed in opaque units by the pricing API", source: "https://fal.ai/models/topaz/upscale/image/precision", verified_at: CHECKED_AT, verified: false },
        notes: "No fal-ai/ prefix. Siblings topaz/upscale/image/{generative,creative,transparent} (Higgsfield topaz_image_generative) are not wired.",
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "topaz/image-upscale",
        priority: 20,
        input: { prompt: null, aspect_ratio: null, count: null, roles: { image: "image_url" }, params: { upscale_factor: "upscale_factor" }, strictParams: true },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.05, notes: "estimate pending a first billed run (Kie reports creditsConsumed); a third-party list shows 2K $0.05, 4K $0.10, 8K $0.20, a community tracker a flat 4 credits", source: `https://kie.ai/topaz-image-upscale (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: false },
        notes: `${SHAPE_VERIFIED}. Body: image_url + upscale_factor as a number. The verified shape sends 2 or 4; the 1 and 8 options come from the docs mirror and are not exercised.`,
        verified: true,
      },
    ],
  },
  {
    id: "upscale_image_clarity",
    name: "Clarity Upscaler",
    vendor: "fal",
    description: "Clarity creative upscaler (2x-4x) with optional prompt guidance; substitute for the ByteDance 2K/4K image upscaler, which has no fal/Kie endpoint.",
    output_type: "image",
    capabilities: ["upscale-image"],
    parameters: [upscaleFactorParam([2, 3, 4], 2), clarityCreativityParam, clarityResemblanceParam, seedParam, safetyParam],
    medias: [sourceImageSlot],
    aspect_ratios: [],
    max_count: 1,
    tags: ["upscale", "creative", "utility", "substitute"],
    higgsfield_ids: ["bytedance_image_upscale"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/clarity-upscaler",
        priority: 10,
        input: {
          aspect_ratio: null,
          count: null,
          roles: { image: "image_url" },
          params: { upscale_factor: "upscale_factor", creativity: "creativity", resemblance: "resemblance", seed: "seed", enable_safety_checker: "enable_safety_checker" },
          strictParams: true,
        },
        output: FAL_IMAGE_OUTPUT,
        pricing: { unit: "megapixel", usd: 0.03, scale_param: { name: "upscale_factor", exponent: 2 }, notes: "billed on output megapixels (source MP x factor squared)", source: "https://fal.ai/models/fal-ai/clarity-upscaler", verified_at: CHECKED_AT, verified: false },
        notes: "Prompt is optional (defaults upstream to 'masterpiece, best quality, highres'). fal only; Kie's nearest substitute is recraft/crisp-upscale (2 credits), not wired. fal-ai/bytedance-upscaler/upscale/image does NOT exist (confirmed absent).",
        verified: false,
      },
    ],
  },
  {
    id: "remove_background",
    name: "Remove Background",
    vendor: "Bria",
    description: "Cut out the subject of an image with a transparent background (Bria RMBG 2.0; BiRefNet v2 and Recraft as alternatives).",
    output_type: "image",
    capabilities: ["background-removal"],
    parameters: [birefnetModelParam],
    medias: [sourceImageSlot],
    aspect_ratios: [],
    max_count: 1,
    tags: ["background-removal", "cutout", "product", "utility"],
    higgsfield_ids: ["image_background_remover"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/bria/background/remove",
        priority: 10,
        input: { prompt: null, aspect_ratio: null, count: null, roles: { image: "image_url" }, params: { model: omit("model") }, strictParams: true },
        output: FAL_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.018, source: "https://fal.ai/models/fal-ai/bria/background/remove", verified_at: CHECKED_AT, verified: false },
        notes: "Replace variant: fal-ai/bria/background/replace.",
        verified: false,
      },
      {
        provider: "fal",
        endpoint: "fal-ai/birefnet/v2",
        priority: 15,
        input: { prompt: null, aspect_ratio: null, count: null, roles: { image: "image_url" }, params: { model: "model" }, strictParams: true },
        output: FAL_IMAGE_OUTPUT,
        notes: "Open-weight alternative billed per compute-second ($0.0008/s, not payload-derivable, so no static price). Also returns mask_image.",
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "recraft/remove-background",
        priority: 20,
        input: { prompt: null, aspect_ratio: null, count: null, roles: { image: "image" }, params: { model: omit("model") }, strictParams: true },
        output: KIE_IMAGE_OUTPUT,
        pricing: { unit: "image", usd: 0.005, notes: "1 credit per image, measured on a billed run on 2026-09-03 (an older mirror listed 2 credits)", source: `https://kie.ai/recraft-remove-background (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Substitute model (Recraft); the body is just { image }.`,
        verified: true,
      },
    ],
  },
  {
    id: "outpaint",
    name: "FLUX.2 Pro Outpaint",
    vendor: "Black Forest Labs",
    description: "Extend an image beyond its borders with FLUX.2 [pro] (photoreal outpainting; pixels per side).",
    output_type: "image",
    capabilities: ["outpaint"],
    parameters: [expandParam("left"), expandParam("right"), expandParam("top"), expandParam("bottom"), seedParam, safetyParam, outputFormatParam(["png", "jpeg"], "png")],
    medias: [sourceImageSlot],
    aspect_ratios: [],
    max_count: 4,
    tags: ["outpaint", "image-edit", "photorealism", "utility"],
    higgsfield_ids: ["flux_2_pro_outpaint", "outpaint"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/flux-2-pro/outpaint",
        priority: 10,
        input: {
          aspect_ratio: null,
          count: { field: "num_images", max: 4 },
          roles: { image: "image_url" },
          params: {
            expand_left: "expand_left",
            expand_right: "expand_right",
            expand_top: "expand_top",
            expand_bottom: "expand_bottom",
            seed: "seed",
            enable_safety_checker: "enable_safety_checker",
            output_format: "output_format",
          },
          strictParams: true,
        },
        output: FAL_IMAGES_OUTPUT,
        pricing: { unit: "megapixel", usd: 0.015, first_unit_usd: 0.03, notes: "same rate as fal-ai/flux-2-pro (first MP $0.03, then $0.015/MP, input+output); the output size follows the source plus the expansion", source: "https://fal.ai/models/fal-ai/flux-2-pro/outpaint/api", verified_at: CHECKED_AT, verified: false },
        notes: "Prompt is optional. fal only: Kie has no dedicated outpaint; ideogram/v3-reframe (5 credits) is the substitute but its input fields are not documented in our sources. Alternatives on fal: fal-ai/bria/expand, fal-ai/ideogram/v3/reframe.",
        verified: false,
      },
    ],
  },
  {
    id: "upscale_video_topaz",
    name: "Topaz Video Upscale",
    vendor: "Topaz Labs",
    description: "Topaz Video AI precision upscaling (up to 4K); output length follows the source clip.",
    output_type: "video",
    capabilities: ["upscale-video"],
    parameters: [topazVideoFactorParam],
    medias: [sourceVideoSlot],
    aspect_ratios: [],
    max_count: 1,
    tags: ["upscale", "topaz", "video", "utility"],
    higgsfield_ids: ["topaz_video", "video_upscale"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "topaz/upscale/video/precision",
        priority: 10,
        input: { prompt: null, aspect_ratio: null, duration: null, count: null, roles: { video: "video_url" }, params: { upscale_factor: "upscale_factor" }, strictParams: true },
        output: FAL_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.02, notes: "$0.10 per 10 s of output at 720p, $0.20 at 1080p, $0.60 at 4K (= $0.01 / $0.02 / $0.06 per second, keyed on OUTPUT resolution, x2 at 60 fps); base assumes 1080p output (output = source length)", input_dependent: true, source: "https://fal.ai/models/topaz/upscale/video/precision", verified_at: CHECKED_AT, verified: true },
        notes: "No fal-ai/ prefix (legacy fal-ai/topaz/upscale/video still indexed). Also accepts target_fps upstream. Siblings topaz/upscale/video/{generative,creative}.",
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "topaz/video-upscale",
        priority: 20,
        input: { prompt: null, aspect_ratio: null, duration: null, count: null, roles: { video: "video_url" }, params: { upscale_factor: { field: "upscale_factor", values: { "1": "1", "2": "2", "4": "4" } } }, strictParams: true },
        output: KIE_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.04, modifiers: [{ when: { upscale_factor: 4 }, usd: 0.07 }], notes: "1x/2x $0.04/s, 4x $0.07/s (third-party list); a community tracker lists a flat 8 credits", input_dependent: true, source: "https://kie.ai/topaz-video-upscaler", verified_at: CHECKED_AT, verified: false },
        notes: "video_url <= 50 MB (MP4/MOV/MKV); upscale_factor is a string enum on the wire.",
        verified: false,
      },
    ],
  },
  {
    id: "upscale_video_bytedance",
    name: "ByteDance Video Upscale",
    vendor: "ByteDance",
    description: "ByteDance video upscaler to 1080p / 2K / 4K - by far the cheapest video upscaler.",
    output_type: "video",
    capabilities: ["upscale-video"],
    parameters: [targetResolutionParam],
    medias: [sourceVideoSlot],
    aspect_ratios: [],
    max_count: 1,
    tags: ["upscale", "budget", "video", "utility"],
    higgsfield_ids: ["bytedance_video_upscale"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/bytedance-upscaler/upscale/video",
        priority: 10,
        input: { prompt: null, aspect_ratio: null, duration: null, count: null, roles: { video: "video_url" }, params: { target_resolution: "target_resolution" }, strictParams: true },
        output: FAL_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.0072,
          modifiers: [
            { when: { target_resolution: "2k" }, usd: 0.0144 },
            { when: { target_resolution: "4k" }, usd: 0.0288 },
          ],
          notes: "per output second at 30 fps; 60 fps doubles; Pro mode 10x",
          input_dependent: true,
          source: "https://fal.ai/models/fal-ai/bytedance-upscaler/upscale/video",
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: "fal only (nothing comparable on Kie). The resolution field name (target_resolution) is assumed - verify. No image variant exists.",
        verified: false,
      },
    ],
  },
  {
    id: "reframe_video",
    name: "Luma Reframe",
    vendor: "Luma",
    description: "Generative video reframing (Luma Ray 3.2): change a clip's aspect ratio while extending the frame, optionally guided by a prompt.",
    output_type: "video",
    capabilities: ["reframe-video"],
    parameters: [],
    medias: [sourceVideoSlot],
    aspect_ratios: ["16:9", "9:16", "1:1", "4:3", "3:4", "21:9", "9:21"],
    max_count: 1,
    tags: ["reframe", "aspect-ratio", "video", "utility"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "luma/agent/ray/v3.2/reframe",
        priority: 10,
        input: { aspect_ratio: { field: "aspect_ratio" }, duration: null, count: null, roles: { video: "video_url" }, strictParams: true },
        output: FAL_VIDEO_OUTPUT,
        notes: "Price not captured by the research (no static pricing). fal only: Kie has no video reframe. Older ids fal-ai/luma-dream-machine/ray-2/reframe and ray-2-flash/reframe (aspect enum 1:1, 16:9, 9:16, 4:3, 3:4, 21:9, 9:21). Prompt is optional guidance. Non-generative crops should use ffmpeg + fal-ai/sam-3/video tracking instead.",
        verified: false,
      },
    ],
  },
  {
    id: "video_background_removal",
    name: "Video Background Removal",
    vendor: "Bria",
    description: "Remove / matte the background of a video (Bria video background removal; BiRefNet v2 video as the open-weight alternative).",
    output_type: "video",
    capabilities: ["video-background-removal"],
    parameters: [],
    medias: [sourceVideoSlot],
    aspect_ratios: [],
    max_count: 1,
    tags: ["background-removal", "matting", "video", "utility"],
    higgsfield_ids: ["video_background_remover"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "bria/video/background-removal",
        priority: 10,
        input: { prompt: null, aspect_ratio: null, duration: null, count: null, roles: { video: "video_url" }, strictParams: true },
        output: FAL_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.14, notes: "third-party figure (30 s = $4.20); realtime variant $0.0033/s; v3 at bria/video/background-removal/v3", input_dependent: true, source: "https://fal.ai/models/bria/video/background-removal", verified_at: CHECKED_AT, verified: false },
        notes: "fal only: Kie has no video background removal (confirmed absent).",
        verified: false,
      },
      {
        provider: "fal",
        endpoint: "fal-ai/birefnet/v2/video",
        priority: 20,
        input: { prompt: null, aspect_ratio: null, duration: null, count: null, roles: { video: "video_url" }, strictParams: true },
        output: FAL_VIDEO_OUTPUT,
        notes: "Open-weight alternative billed per compute-second (not payload-derivable, so no static price).",
        verified: false,
      },
    ],
  },
];
