import type { ModelDefinition, ModelParameter } from "../types";
import {
  AR_GROK,
  AR_VIDEO_COMMON,
  AR_VIDEO_VEO,
  AR_VIDEO_WAN,
  AR_VIDEO_WIDE,
  PRICES_CHECKED,
  SHAPE_VERIFIED,
  CHECKED_AT,
  FAL_VIDEO_OUTPUT,
  KIE_VIDEO_OUTPUT,
  audioRefsSlot,
  cfgScaleParam,
  characterOrientationParam,
  drivingVideoSlot,
  elementsParam,
  endImageSlot,
  generateAudioParam,
  imageRefsSlot,
  modeParam,
  multiPromptParam,
  omit,
  promptOptimizerParam,
  referenceImageSlot,
  resolutionParam,
  returnLastFrameParam,
  safetyParam,
  seedParam,
  shotTypeParam,
  startImageSlot,
  videoRefsSlot,
} from "./_shared";

/**
 * Video generation models (MVP scope).
 *
 * fal exposes one endpoint per input mode (text / image / first-last / reference),
 * so every fal binding carries `endpointByMode` and the app resolves the endpoint
 * from the media roles with `resolveEndpoint()`. Kie usually has one slug per
 * model family that switches mode by which fields are sent, so a shared roles map
 * is enough there. Prices are USD list prices seen Aug/Sep 2026 (Kie: credits x
 * $0.005); `verified: true` on pricing = confirmed by the 2026-09-05 fact-check.
 */

const klingModeParam = modeParam(["std", "pro", "4k"], "pro", "Kling tier: std = 720p, pro = 1080p, 4k. On fal the binding is pinned to the pro endpoints (std/4k tiers need the v3/standard or v3/4k endpoints); on Kie it maps to the omni `resolution` (720p / 1080p / 4k).");
const motionModeParam = modeParam(["std", "pro"], "std", "Output quality: std = 720p, pro = 1080p (Kie `mode`; fal binding is pinned to the pro endpoint).");
const backgroundSourceParam: ModelParameter = {
  name: "background_source",
  type: "string",
  required: false,
  description: "Motion control background: keep the driving video's background or use the image's (Kie only).",
  default: "input_video",
  options: ["input_video", "input_image"],
};
const veoGenerationTypeParam: ModelParameter = {
  name: "generation_type",
  type: "string",
  required: false,
  description: "Kie Veo mode override (auto-detected from imageUrls when omitted): TEXT_2_VIDEO, FIRST_AND_LAST_FRAMES_2_VIDEO (1-2 images) or REFERENCE_2_VIDEO (1-3 material images; Fast/Lite only).",
  options: ["TEXT_2_VIDEO", "FIRST_AND_LAST_FRAMES_2_VIDEO", "REFERENCE_2_VIDEO"],
};
const veoTranslationParam: ModelParameter = { name: "enable_translation", type: "boolean", required: false, description: "Kie: translate non-English prompts before generation.", default: true };
const grokModeParam: ModelParameter = { name: "mode", type: "string", required: false, description: "Grok content mode (Kie only).", default: "normal", options: ["fun", "normal", "spicy"] };
const h3PromptExpansionParam: ModelParameter = { name: "prompt_expansion_mode", type: "string", required: false, description: "MiniMax prompt expansion (fal only).", options: ["auto", "off"] };

export const VIDEO_MODELS: ModelDefinition[] = [
  {
    id: "kling_3_0",
    name: "Kling 3.0",
    vendor: "Kling",
    description: "Kling 3.0 (Omni): cinematic text/image-to-video with native audio, first/last frame, multi-shot storyboards and character elements; 3-15 s, std/pro/4K.",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video"],
    parameters: [klingModeParam, generateAudioParam(false), multiPromptParam, elementsParam, shotTypeParam, cfgScaleParam],
    medias: [startImageSlot, endImageSlot],
    aspect_ratios: [...AR_VIDEO_COMMON],
    duration_range: { min: 3, max: 15 },
    default_duration: 5,
    max_count: 1,
    tags: ["cinematic", "multi-shot", "audio", "elements", "first-last-frame", "advanced"],
    higgsfield_ids: ["kling3_0"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/kling-video/v3/pro/text-to-video",
        endpointByMode: { text: "fal-ai/kling-video/v3/pro/text-to-video", image: "fal-ai/kling-video/v3/pro/image-to-video" },
        pinnedParams: { mode: "pro" },
        priority: 10,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "string" },
          count: null,
          roles: { start_image: "start_image_url", end_image: "end_image_url" },
          params: { mode: omit("mode"), generate_audio: "generate_audio", multi_prompt: "multi_prompt", elements: "elements", shot_type: "shot_type", cfg_scale: "cfg_scale" },
          byMode: { image: { aspect_ratio: null } },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.112,
          modifiers: [{ when: { generate_audio: true }, usd: 0.168 }],
          notes: "pro tier; $0.196/s with voice control; standard tier $0.084/$0.126/$0.154 (v3/standard/*), 4K $0.42/s flat (v3/4k/*)",
          source: `https://fal.ai/models/fal-ai/kling-video/v3/pro/text-to-video (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Body: prompt, duration as a string, generate_audio, plus aspect_ratio on text-to-video or start_image_url/end_image_url (no aspect_ratio) on image-to-video (first_last falls back to it). Pinned to the pro endpoints (pinnedParams): std lives on v3/standard and 4k on v3/4k with the same fields, which endpointByMode cannot express, so other tiers route to Kie. negative_prompt, multi_prompt (needs shot_type customize), elements ([{ frontal_image_url, reference_image_urls[] }], @Element1..) and cfg_scale are pass-through extras outside the verified shape. Reference-to-video only exists on the O3 family (fal-ai/kling-video/o3/*).`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "kling-3.0-omni/text-to-video",
        endpointByMode: { text: "kling-3.0-omni/text-to-video", image: "kling-3.0-omni/image-to-video" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "image_urls[]", end_image: "image_urls[]" },
          params: {
            mode: { field: "resolution", values: { std: "720p", pro: "1080p", "4k": "4k" } },
            generate_audio: "audio",
            multi_prompt: omit("multi_prompt"),
            elements: omit("elements"),
            shot_type: omit("shot_type"),
            cfg_scale: omit("cfg_scale"),
          },
          byMode: { image: { aspect_ratio: null, constants: { aspect_ratio: "auto" } } },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.09,
          modifiers: [
            { when: { mode: "4k" }, usd: 0.335 },
            { when: { mode: "std", generate_audio: true }, usd: 0.1 },
            { when: { mode: "std" }, usd: 0.07 },
            { when: { mode: "pro", generate_audio: true }, usd: 0.135 },
          ],
          notes: "720p 14/20 credits, 1080p 18/27 credits per second (no audio / audio); 4k 67 credits regardless of audio",
          source: `https://kie.ai/kling-3-0 (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Replaces the legacy kling-3.0/video slug (mode / sound / multi_shots): the omni family takes resolution 720p|1080p|4k, audio, duration as a number, aspect_ratio 16:9|9:16|1:1 on text-to-video and image_urls = [first, last] with aspect_ratio auto on image-to-video. kling-3.0-omni/reference-to-video (image_urls, up to 7 refs) is not wired; multi_prompt and elements stay fal-only until the omni customize_multi_shots shape is verified.`,
        verified: true,
      },
    ],
  },
  {
    id: "kling_3_0_turbo",
    name: "Kling 3.0 Turbo",
    vendor: "Kling",
    description: "Kling 3.0 Turbo: the fast, budget Kling 3.0 tier for text/image-to-video (3-15 s, 720p/1080p; no end frame).",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video"],
    parameters: [resolutionParam(["720p", "1080p"], "720p", "Output resolution (Kie tier; fal binding is pinned to the turbo/pro endpoints)."), generateAudioParam(false)],
    medias: [startImageSlot],
    aspect_ratios: [...AR_VIDEO_COMMON],
    duration_range: { min: 3, max: 15 },
    default_duration: 5,
    max_count: 1,
    tags: ["fast", "turbo", "budget", "start-frame"],
    higgsfield_ids: ["kling3_0_turbo"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/kling-video/v3/turbo/pro/text-to-video",
        endpointByMode: { text: "fal-ai/kling-video/v3/turbo/pro/text-to-video", image: "fal-ai/kling-video/v3/turbo/pro/image-to-video" },
        pinnedParams: { resolution: "1080p" },
        priority: 10,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "string" },
          count: null,
          roles: { start_image: "start_image_url" },
          params: { resolution: omit("resolution"), generate_audio: "generate_audio" },
          byMode: { image: { aspect_ratio: null } },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.14, notes: "turbo/pro $0.14/s (text- and image-to-video); turbo/standard $0.112/s", source: `https://fal.ai/models/fal-ai/kling-video/v3/turbo/pro/image-to-video (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Same fields as the v3 pro endpoints (string duration, generate_audio, start_image_url without aspect_ratio). Pinned to turbo/pro (1080p); the 720p tier lives on turbo/standard (not wired). Turbo takes no end frame, so end_image is not offered; negative_prompt is a pass-through extra.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "kling/v3-turbo-text-to-video",
        endpointByMode: { text: "kling/v3-turbo-text-to-video", image: "kling/v3-turbo-image-to-video" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "string" },
          count: null,
          roles: { start_image: "image_urls[]" },
          params: { resolution: "resolution", generate_audio: omit("generate_audio") },
          byMode: { image: { aspect_ratio: null } },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.09, modifiers: [{ when: { resolution: "1080p" }, usd: 0.1125 }], notes: "18 / 22.5 credits per second", source: `https://kie.ai/kling-3-0-turbo (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Body: prompt, duration as a string, resolution 720p|1080p, plus aspect_ratio 1:1|9:16|16:9 on text-to-video or image_urls [first] (no aspect_ratio) on image-to-video. No audio toggle and no end frame on the turbo slugs.`,
        verified: true,
      },
    ],
  },
  {
    id: "kling_motion_control",
    name: "Kling 3.0 Motion Control",
    vendor: "Kling",
    description: "Transfer the motion of a driving video onto a character image (Higgsfield Genjutsu motion control); output length follows the driving video (<= 30 s).",
    output_type: "video",
    capabilities: ["motion-control", "video-to-video"],
    parameters: [motionModeParam, characterOrientationParam, backgroundSourceParam],
    medias: [referenceImageSlot, drivingVideoSlot],
    aspect_ratios: [],
    duration_range: { min: 3, max: 30 },
    default_duration: 5,
    max_count: 1,
    tags: ["motion-control", "motion-transfer", "character", "video-reference", "genjutsu"],
    higgsfield_ids: ["hf_mult_motion_control"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/kling-video/v3/pro/motion-control",
        pinnedParams: { mode: "pro" },
        priority: 10,
        input: {
          duration: null,
          count: null,
          roles: { image: "image_url", video: "video_url" },
          params: { mode: omit("mode"), character_orientation: "character_orientation", background_source: omit("background_source") },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.112, notes: "pro tier; $0.168/s with audio; standard tier fal-ai/kling-video/v3/standard/motion-control", input_dependent: true, source: "https://fal.ai/models/fal-ai/kling-video/v3/standard/motion-control/api", verified_at: CHECKED_AT, verified: false },
        notes: "Field names (image_url / video_url / character_orientation) follow fal's v2.6 motion-control schema - verify. `duration` is only used for cost estimates (output length = driving video).",
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "kling-3.0/motion-control",
        priority: 20,
        input: {
          duration: null,
          count: null,
          roles: { image: "input_urls[]", video: "video_urls[]" },
          params: { mode: { field: "mode", values: { std: "720p", pro: "1080p" } }, character_orientation: "character_orientation", background_source: "background_source" },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.1, modifiers: [{ when: { mode: "pro" }, usd: 0.135 }], notes: "20 credits/s (720p) or 27 credits/s (1080p)", input_dependent: true, source: "https://kie.ai/kling-3-0 (Kie pricing copy)", verified_at: CHECKED_AT, verified: true },
        notes: "Image <= 10 MB, > 340 px, aspect 2:5-5:2; video MP4/MOV <= 100 MB, 3-30 s (<= 10 s when character_orientation=image). The doc prose says mode std/pro but the official example and option table send 720p/1080p - the values map follows the example; flip if a live probe 422s.",
        verified: false,
      },
    ],
  },
  {
    id: "seedance_2_0",
    name: "Seedance 2.0",
    vendor: "ByteDance",
    description: "Seedance 2.0: multimodal reference-to-video (up to 9 images, 3 videos, 3 audio clips), first/last frame and text-to-video with native audio; 4-15 s, up to 1080p (4K on Kie).",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video", "reference-to-video"],
    parameters: [resolutionParam(["480p", "720p", "1080p"], "720p"), generateAudioParam(true)],
    medias: [startImageSlot, endImageSlot, imageRefsSlot(9, "Reference images (identity, product, style); mutually exclusive with first/last frame."), videoRefsSlot(3, "Reference videos (2-15 s each, 15 s total)."), audioRefsSlot(3, "Reference audio (2-15 s each).")],
    aspect_ratios: [...AR_VIDEO_WIDE],
    duration_range: { min: 4, max: 15 },
    default_duration: 5,
    max_count: 1,
    tags: ["reference", "identity", "consistent", "product", "audio", "video-reference", "start-frame", "end-frame"],
    higgsfield_ids: ["seedance_2_0"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "bytedance/seedance-2.0/text-to-video",
        endpointByMode: { text: "bytedance/seedance-2.0/text-to-video", image: "bytedance/seedance-2.0/image-to-video", reference: "bytedance/seedance-2.0/reference-to-video" },
        priority: 10,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "string" },
          count: null,
          roles: { start_image: "image_url", end_image: "end_image_url", image_references: "image_urls[]", video_references: "video_urls[]", audio_references: "audio_urls[]" },
          params: { resolution: "resolution", generate_audio: "generate_audio" },
          byMode: { image: { aspect_ratio: null, constants: { aspect_ratio: "auto" } } },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.3034,
          modifiers: [
            { when: { resolution: "480p" }, usd: 0.134 },
            { when: { resolution: "1080p" }, usd: 0.682 },
          ],
          notes: "token formula $0.014/1k tokens (h*w*duration*24/1024), 480p derived from the token rate; video inputs billed at x0.6; fast tier $0.2419/s (720p) at bytedance/seedance-2.0/fast/*",
          source: `https://fal.ai/models/bytedance/seedance-2.0/image-to-video (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Owner prefix bytedance/. Same body as the 2.5 endpoints: duration as a string, resolution, generate_audio, plus aspect_ratio + image_urls on reference-to-video or image_url/end_image_url with aspect_ratio auto on image-to-video (text-to-video was checked against fal's docs; the other modes follow the 2.5 pattern). video_urls/audio_urls are outside the verified shape.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "bytedance/seedance-2",
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "first_frame_url", end_image: "last_frame_url", image_references: "reference_image_urls[]", video_references: "reference_video_urls[]", audio_references: "reference_audio_urls[]" },
          params: { resolution: "resolution", generate_audio: "generate_audio" },
          constants: { output_format: "mp4" },
          byMode: { image: { aspect_ratio: null, constants: { aspect_ratio: "adaptive" } } },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.315,
          modifiers: [
            { when: { resolution: "480p" }, usd: 0.14 },
            { when: { resolution: "1080p" }, usd: 0.57 },
          ],
          notes: "no-video-input rates, identical to seedance-2-5 on the 2026-09-04 price check (an earlier Kie copy listed $0.095 / $0.205 / $0.51); reference video input is billed on input+output seconds at a lower rate; Kie also prices a 4k tier",
          source: `https://kie.ai/seedance-2-0 (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Body: prompt, resolution, aspect_ratio, duration (number), generate_audio, output_format mp4, plus first_frame_url/last_frame_url (aspect_ratio must then be adaptive, 422 otherwise) or reference_image_urls. Frames and reference_* inputs are mutually exclusive; reference_video_urls/reference_audio_urls are outside the verified shape (the 2.0 doc once spelled the video key with a trailing space). nsfw_checker defaults to false upstream.`,
        verified: true,
      },
      {
        provider: "higgsfield",
        endpoint: "bytedance/seedance-2.0/text-to-video",
        supportedModes: ["text"],
        supportedParamValues: { resolution: ["480p", "720p"] },
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          params: { resolution: "resolution", generate_audio: "generate_audio" },
          strictParams: true,
        },
        output: { outputs: [{ path: "video", kind: "video" }] },
        pricing: { unit: "second", usd: 0.3024, modifiers: [{ when: { resolution: "480p" }, usd: 0.1407 }], source: "https://open.higgsfield.ai/models/bytedance/seedance-2.0/text-to-video/playground", verified_at: "2026-09-28", verified: false, notes: "Conservative pre-discount 16:9 estimate; actual charge varies with dimensions, sale and cashback. The API returns a descriptive formula rather than numerical USD." },
        notes: "Text-to-video endpoint and sample body are documented by Higgsfield. Reference modes and 1080p pricing are not wired. Live video generation pending.",
        verified: false,
      },
    ],
  },
  {
    id: "seedance_2_0_mini",
    name: "Seedance 2.0 Mini",
    vendor: "ByteDance",
    description: "Seedance 2.0 Mini: the budget multimodal Seedance (references, first/last frame, audio) at 480p/720p.",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video", "reference-to-video"],
    parameters: [resolutionParam(["480p", "720p"], "720p"), generateAudioParam(true)],
    medias: [startImageSlot, endImageSlot, imageRefsSlot(9, "Reference images; mutually exclusive with first/last frame."), videoRefsSlot(3), audioRefsSlot(3)],
    aspect_ratios: [...AR_VIDEO_WIDE],
    duration_range: { min: 4, max: 15 },
    default_duration: 5,
    max_count: 1,
    tags: ["fast", "budget", "reference", "identity", "audio", "start-frame", "end-frame"],
    higgsfield_ids: ["seedance_2_0_mini"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "bytedance/seedance-2.0/mini/text-to-video",
        endpointByMode: { text: "bytedance/seedance-2.0/mini/text-to-video", image: "bytedance/seedance-2.0/mini/image-to-video", reference: "bytedance/seedance-2.0/mini/reference-to-video" },
        priority: 10,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "string" },
          count: null,
          roles: { start_image: "image_url", end_image: "end_image_url", image_references: "image_urls[]", video_references: "video_urls[]", audio_references: "audio_urls[]" },
          params: { resolution: "resolution", generate_audio: "generate_audio" },
          byMode: { image: { aspect_ratio: null, constants: { aspect_ratio: "auto" } } },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.1547, modifiers: [{ when: { resolution: "480p" }, usd: 0.0721 }], notes: "$0.007/1k tokens; video inputs x0.6", source: `https://fal.ai/models/bytedance/seedance-2.0/mini/reference-to-video (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Same body as seedance_2_0 on fal (string duration, aspect_ratio auto with a start frame).`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "bytedance/seedance-2-mini",
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "first_frame_url", end_image: "last_frame_url", image_references: "reference_image_urls[]", video_references: "reference_video_urls[]", audio_references: "reference_audio_urls[]" },
          params: { resolution: "resolution", generate_audio: "generate_audio" },
          constants: { output_format: "mp4" },
          byMode: { image: { aspect_ratio: null, constants: { aspect_ratio: "adaptive" } } },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.041, modifiers: [{ when: { resolution: "480p" }, usd: 0.019 }], notes: "no-video-input rates (8.2 / 3.8 credits); with reference video input 720p $0.025, 480p $0.012 per (input+output) second (price cut 2026-08-26)", source: `https://kie.ai/seedance-2-0-mini (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Same body as bytedance/seedance-2 (output_format mp4, aspect_ratio adaptive with a start frame; see its notes).`,
        verified: true,
      },
    ],
  },
  {
    id: "seedance_2_5",
    name: "Seedance 2.5",
    vendor: "ByteDance",
    description: "Seedance 2.5: long-form (4-30 s) multimodal generation and video editing - up to 30 image, 10 video and 10 audio references; the Ad Multiplier workhorse.",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video", "reference-to-video", "video-edit", "video-extension"],
    parameters: [resolutionParam(["480p", "720p", "1080p"], "720p", "Output resolution (native 480p/720p; treat 1080p as an upscaled tier)."), generateAudioParam(true), returnLastFrameParam],
    medias: [startImageSlot, endImageSlot, imageRefsSlot(30, "Reference images (<= 50 references in total across modalities)."), videoRefsSlot(10, "Reference / source videos to edit or extend."), audioRefsSlot(10)],
    aspect_ratios: [...AR_VIDEO_WIDE],
    duration_range: { min: 4, max: 30 },
    default_duration: 5,
    max_count: 1,
    tags: ["reference", "identity", "video-edit", "video-extension", "long-form", "audio", "ad-multiplier"],
    higgsfield_ids: ["seedance_2_5", "ad_multiplier"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "bytedance/seedance-2.5/text-to-video",
        endpointByMode: { text: "bytedance/seedance-2.5/text-to-video", image: "bytedance/seedance-2.5/image-to-video", reference: "bytedance/seedance-2.5/reference-to-video" },
        priority: 10,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "string" },
          count: null,
          roles: { start_image: "image_url", end_image: "end_image_url", image_references: "image_urls[]", video_references: "video_urls[]", audio_references: "audio_urls[]" },
          params: { resolution: "resolution", generate_audio: "generate_audio", return_last_frame: "return_last_frame" },
          byMode: { image: { aspect_ratio: null, constants: { aspect_ratio: "auto" } } },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.473,
          modifiers: [
            { when: { resolution: "480p" }, usd: 0.2205 },
            { when: { resolution: "1080p" }, usd: 1.164 },
          ],
          notes: "token-billed: $0.0214/1k tokens at 480p/720p (~$0.0234 at 1080p, so the 1080p rate is approximate); tokens = h*w*(input+output duration)*24/1024; x0.6 with video inputs",
          source: `https://fal.ai/models/bytedance/seedance-2.5/reference-to-video (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Body: prompt, resolution, duration as a string, generate_audio, plus aspect_ratio + image_urls (<= 30) on reference-to-video or image_url/end_image_url with aspect_ratio auto on image-to-video. video_urls (<= 10), audio_urls (<= 10) and return_last_frame are outside the verified shape (audited separately, 2026-09-02); extension/edit = reference-to-video with the clip as a video reference.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "bytedance/seedance-2-5",
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "first_frame_url", end_image: "last_frame_url", image_references: "reference_image_urls[]", video_references: "reference_video_urls[]", audio_references: "reference_audio_urls[]" },
          params: { resolution: "resolution", generate_audio: "generate_audio", return_last_frame: "return_last_frame" },
          constants: { output_format: "mp4" },
          byMode: { image: { aspect_ratio: null, constants: { aspect_ratio: "adaptive" } } },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.315,
          modifiers: [
            { when: { resolution: "480p" }, usd: 0.14 },
            { when: { resolution: "1080p" }, usd: 0.57 },
          ],
          notes: "no-video-input rates (28 / 63 credits per second); with reference video input 480p $0.085, 720p $0.19, 1080p $0.3425 per (input video + output) second",
          source: `https://kie.ai/seedance-2-5 (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Body: prompt, resolution, aspect_ratio, duration (number), generate_audio, output_format mp4, plus first_frame_url/last_frame_url (aspect_ratio must then be adaptive, 422 otherwise) or reference_image_urls. reference_video_urls/reference_audio_urls, return_last_frame and the undocumented extension_task_id are outside the verified shape. Most expensive per second on Kie - reconcile with creditsConsumed.`,
        verified: true,
      },
      {
        provider: "higgsfield",
        endpoint: "bytedance/seedance-2.5/text-to-video",
        supportedModes: ["text"],
        supportedParamValues: { resolution: ["480p", "720p"], return_last_frame: [false] },
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          params: { resolution: "resolution", generate_audio: "generate_audio", return_last_frame: omit("return_last_frame") },
          constants: { output_format: "mp4" },
          strictParams: true,
        },
        output: { outputs: [{ path: "video", kind: "video" }] },
        pricing: { unit: "second", usd: 0.4622, modifiers: [{ when: { resolution: "480p" }, usd: 0.2056 }], source: "https://open.higgsfield.ai/models/bytedance/seedance-2.5/text-to-video/api-reference", verified_at: "2026-09-28", verified: false, notes: "Conservative pre-discount 16:9 rate from the API's descriptive estimate; actual charge varies with dimensions, sale and cashback." },
        notes: "Official Higgsfield API text-to-video route supports 4-30 s, 480p/720p, aspect ratio, mp4/mov and audio. Reference modes and return_last_frame are not wired. The account estimate endpoint returns a pricing description, not numerical USD.",
        verified: false,
      },
    ],
  },
  {
    id: "veo_3_1",
    name: "Veo 3.1",
    vendor: "Google",
    description: "Google Veo 3.1 (quality): ultra-realistic cinematic video with native audio; text, image, first/last frame and reference modes; up to 4K.",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video", "reference-to-video"],
    parameters: [resolutionParam(["720p", "1080p", "4K"], "720p"), generateAudioParam(true), veoGenerationTypeParam, veoTranslationParam, seedParam],
    medias: [startImageSlot, endImageSlot, imageRefsSlot(3, "Up to 3 material / reference images (reference-to-video).")],
    aspect_ratios: [...AR_VIDEO_VEO],
    durations: [4, 6, 8],
    default_duration: 8,
    max_count: 1,
    tags: ["ultra-realistic", "cinematic", "top-tier", "quality", "audio"],
    higgsfield_ids: ["veo3_1", "veo3"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/veo3.1",
        endpointByMode: { text: "fal-ai/veo3.1", image: "fal-ai/veo3.1/image-to-video", reference: "fal-ai/veo3.1/reference-to-video" },
        supportedModes: ["text", "image", "reference"],
        priority: 10,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "seconds_suffix" },
          count: null,
          roles: { start_image: "image_url", image_references: "image_urls[]" },
          params: { resolution: "resolution", generate_audio: "generate_audio", generation_type: omit("generation_type"), enable_translation: omit("enable_translation"), seed: "seed" },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.4,
          modifiers: [
            { when: { resolution: "4K", generate_audio: false }, usd: 0.4 },
            { when: { resolution: "4K" }, usd: 0.6 },
            { when: { generate_audio: false }, usd: 0.2 },
          ],
          notes: "720p/1080p $0.20/s without audio, $0.40/s with audio; 4K $0.40/$0.60",
          source: "https://fal.ai/models/fal-ai/veo3.1",
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes:
          "Duration is sent as `8s`. The first-last-frame endpoint (fal-ai/veo3.1/first-last-frame-to-video) uses different field names (first_frame_url/last_frame_url, unverified) than image-to-video (image_url), so it is not wired: first/last-frame requests route to the Kie binding (imageUrls[2]). Extend: fal-ai/veo3.1/extend-video.",
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "veo3",
        family: "veo",
        supportedModes: ["text", "image", "first_last"],
        fixedDuration: 8,
        pinnedParams: { generate_audio: true },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: null,
          count: null,
          roles: { start_image: "imageUrls[]", end_image: "imageUrls[]" },
          params: {
            resolution: { field: "resolution", values: { "720p": "720p", "1080p": "1080p", "4K": "4k" } },
            generate_audio: omit("generate_audio"),
            generation_type: "generationType",
            enable_translation: "enableTranslation",
            seed: omit("seed"),
          },
          constants: { model: "veo3" },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: {
          unit: "generation",
          usd: 1.25,
          modifiers: [
            { when: { resolution: "1080p" }, usd: 1.275 },
            { when: { resolution: "4K" }, usd: 1.85 },
          ],
          notes: "per 8 s clip (250 credits at 720p); earlier marketing $2.00 and a June probe of 400 credits are stale",
          source: "https://kie.ai/veo-3-1 (third-party price pull 2026-08-06)",
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes:
          "Veo family: POST /api/v1/veo/generate with the body at top level (model, prompt, imageUrls[1-2], aspect_ratio 16:9|9:16|Auto, resolution, generationType, enableTranslation). Clips are fixed at 8 s (fixedDuration) and audio is always on (pinnedParams), both reported as adjustments. REFERENCE_2_VIDEO is Fast/Lite only, so reference requests route to fal. 1080p/4K are delivered through get-1080p-video / get-4k-video upgrade tasks (not wired; unverified whether generate honours resolution directly).",
        verified: false,
      },
    ],
  },
  {
    id: "veo_3_1_fast",
    name: "Veo 3.1 Fast",
    vendor: "Google",
    description: "Google Veo 3.1 Fast: the cost-efficient Veo tier with audio; supports reference-to-video (up to 3 material images).",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video", "reference-to-video"],
    parameters: [resolutionParam(["720p", "1080p", "4K"], "720p"), generateAudioParam(true), veoGenerationTypeParam, veoTranslationParam, seedParam],
    medias: [startImageSlot, endImageSlot, imageRefsSlot(3, "Up to 3 material / reference images (reference-to-video).")],
    aspect_ratios: [...AR_VIDEO_VEO],
    durations: [4, 6, 8],
    default_duration: 8,
    max_count: 1,
    tags: ["fast", "cost-efficient", "audio", "reference"],
    higgsfield_ids: ["veo3_1"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/veo3.1/fast",
        endpointByMode: { text: "fal-ai/veo3.1/fast", image: "fal-ai/veo3.1/fast/image-to-video", reference: "fal-ai/veo3.1/fast/reference-to-video" },
        supportedModes: ["text", "image", "reference"],
        priority: 10,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "seconds_suffix" },
          count: null,
          roles: { start_image: "image_url", image_references: "image_urls[]" },
          params: { resolution: "resolution", generate_audio: "generate_audio", generation_type: omit("generation_type"), enable_translation: omit("enable_translation"), seed: "seed" },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.15,
          modifiers: [
            { when: { resolution: "4K", generate_audio: false }, usd: 0.3 },
            { when: { resolution: "4K" }, usd: 0.35 },
            { when: { generate_audio: false }, usd: 0.1 },
          ],
          notes: "720p/1080p $0.10/s without audio, $0.15/s with audio; 4K $0.30/$0.35",
          source: "https://fal.ai/models/fal-ai/veo3.1/fast",
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: "See veo_3_1: first-last-frame endpoint (fal-ai/veo3.1/fast/first-last-frame-to-video) not wired; first/last-frame requests route to Kie.",
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "veo3_fast",
        family: "veo",
        fixedDuration: 8,
        pinnedParams: { generate_audio: true },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: null,
          count: null,
          roles: { start_image: "imageUrls[]", end_image: "imageUrls[]", image_references: "imageUrls[]" },
          params: {
            resolution: { field: "resolution", values: { "720p": "720p", "1080p": "1080p", "4K": "4k" } },
            generate_audio: omit("generate_audio"),
            generation_type: "generationType",
            enable_translation: "enableTranslation",
            seed: omit("seed"),
          },
          constants: { model: "veo3_fast" },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: {
          unit: "generation",
          usd: 0.3,
          modifiers: [
            { when: { resolution: "1080p" }, usd: 0.325 },
            { when: { resolution: "4K" }, usd: 0.9 },
          ],
          notes: "per 8 s clip (60 credits at 720p, cut from 80; a June probe measured 168 credits) - reconcile with creditsConsumed",
          source: "https://kie.ai/veo-3-1 (third-party price pull 2026-08-06)",
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: "Reference mode: set generation_type=REFERENCE_2_VIDEO with 1-3 image_references (16:9 / 9:16 only). Otherwise as veo_3_1.",
        verified: false,
      },
    ],
  },
  {
    id: "veo_3_1_lite",
    name: "Veo 3.1 Lite",
    vendor: "Google",
    description: "Google Veo 3.1 Lite: the budget Veo tier for batch and high-volume generation (720p/1080p).",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video"],
    parameters: [resolutionParam(["720p", "1080p"], "720p"), generateAudioParam(true), veoGenerationTypeParam, veoTranslationParam, seedParam],
    medias: [startImageSlot, endImageSlot],
    aspect_ratios: [...AR_VIDEO_VEO],
    durations: [4, 6, 8],
    default_duration: 8,
    max_count: 1,
    tags: ["fast", "budget", "affordable", "batch", "lite"],
    higgsfield_ids: ["veo3_1_lite"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/veo3.1/lite",
        endpointByMode: { text: "fal-ai/veo3.1/lite", image: "fal-ai/veo3.1/lite/image-to-video" },
        supportedModes: ["text", "image"],
        priority: 10,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "seconds_suffix" },
          count: null,
          roles: { start_image: "image_url" },
          params: { resolution: "resolution", generate_audio: "generate_audio", generation_type: omit("generation_type"), enable_translation: omit("enable_translation"), seed: "seed" },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.05,
          modifiers: [
            { when: { resolution: "1080p", generate_audio: false }, usd: 0.05 },
            { when: { resolution: "1080p" }, usd: 0.08 },
            { when: { generate_audio: false }, usd: 0.03 },
          ],
          notes: "720p $0.03/$0.05, 1080p $0.05/$0.08 per second (no audio / audio)",
          source: "https://fal.ai/models/fal-ai/veo3.1/lite",
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: "fal-ai/veo3.1/lite/first-last-frame-to-video exists but is not wired (see veo_3_1); no lite reference-to-video on fal.",
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "veo3_lite",
        family: "veo",
        supportedModes: ["text", "image", "first_last"],
        fixedDuration: 8,
        pinnedParams: { generate_audio: true },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: null,
          count: null,
          roles: { start_image: "imageUrls[]", end_image: "imageUrls[]" },
          params: {
            resolution: "resolution",
            generate_audio: omit("generate_audio"),
            generation_type: "generationType",
            enable_translation: "enableTranslation",
            seed: omit("seed"),
          },
          constants: { model: "veo3_lite" },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: { unit: "generation", usd: 0.15, modifiers: [{ when: { resolution: "1080p" }, usd: 0.175 }], notes: "per 8 s clip (30 credits at 720p); 4K upgrade $0.75", source: "https://kie.ai/veo-3-1 (third-party price pull 2026-08-06)", verified_at: CHECKED_AT, verified: true },
        notes: "Live docs say REFERENCE_2_VIDEO now also works on Lite; not exposed here until confirmed. Otherwise as veo_3_1.",
        verified: false,
      },
    ],
  },
  {
    id: "wan_3_0",
    name: "Wan 3.0",
    vendor: "Alibaba",
    description: "Wan 3.0: up to 30 s of 1080p video with native audio from text, first/last frame or multimodal references (10 images, 5 videos, 5 audio clips).",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video", "reference-to-video"],
    parameters: [resolutionParam(["480p", "720p", "1080p"], "720p"), generateAudioParam(true), seedParam],
    medias: [startImageSlot, endImageSlot, imageRefsSlot(10, "Reference images, addressed as Image1, Image2..."), videoRefsSlot(5, "Reference videos (1-15 s each; input + output <= 30 s)."), audioRefsSlot(5)],
    aspect_ratios: [...AR_VIDEO_WAN],
    duration_range: { min: 2, max: 30 },
    default_duration: 5,
    max_count: 1,
    tags: ["long-form", "reference", "identity", "audio", "first-last-frame", "1080p"],
    higgsfield_ids: ["wan3_0", "wan3_0_prime"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "alibaba/wan-3.0/text-to-video",
        endpointByMode: { text: "alibaba/wan-3.0/text-to-video", image: "alibaba/wan-3.0/image-to-video", reference: "alibaba/wan-3.0/reference-to-video" },
        priority: 10,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "image_url", end_image: "end_image_url", image_references: "image_urls[]", video_references: "video_urls[]", audio_references: "audio_urls[]" },
          params: { resolution: "resolution", generate_audio: "generate_audio", seed: "seed" },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.1,
          modifiers: [
            { when: { resolution: "480p" }, usd: 0.05 },
            { when: { resolution: "1080p" }, usd: 0.2 },
          ],
          notes: "model-page rates; fal's pricing API actually bills these endpoints per compute-second ($0.00017/s GPU) so the estimate is indicative only. Prime tier alibaba/wan-3.0-prime/* bills $0.05 per output second flat",
          source: "https://fal.ai/models/alibaba/wan-3.0/text-to-video",
          verified_at: CHECKED_AT,
          verified: false,
        },
        notes: "Owner prefix `alibaba/`. Field names follow fal's Seedance/H3 conventions (image_url/end_image_url, image_urls/video_urls/audio_urls, generate_audio) - unverified; run catalog:verify before use.",
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "wan/3-0-video",
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "first_frame_url", end_image: "last_frame_url", image_references: "reference_image_urls[]", video_references: "reference_video_urls[]", audio_references: "reference_audio_urls[]" },
          params: { resolution: { field: "resolution", values: { "480p": "480P", "720p": "720P", "1080p": "1080P" } }, generate_audio: "audio", seed: "seed" },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.16, modifiers: [{ when: { resolution: "480p" }, usd: 0.04 }], notes: "8 / 16 / 32 credits per (input + output) second at 480P / 720P / 1080P (published 2026-08-26); prime slug wan/3-0-video-prime $0.0612 / $0.126 / $0.252", source: "https://kie.ai/wan-3-0-video?model=wan%2F3-0-video", verified_at: CHECKED_AT, verified: false },
        notes: "Resolution values are UPPERCASE on the wire. Also accepts reference_file_urls / reference_link_urls, duration -1 (smart) and nsfw_checker. Frames and reference_* inputs are mutually exclusive.",
        verified: false,
      },
    ],
  },
  {
    id: "wan_2_7",
    name: "Wan 2.7",
    vendor: "Alibaba",
    description: "Wan 2.7: character-consistent video with synced native audio from text, first/last frame or reference images; 2-15 s at 720p/1080p (reference mode <= 10 s).",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video", "reference-to-video"],
    parameters: [resolutionParam(["720p", "1080p"], "720p"), seedParam],
    medias: [startImageSlot, endImageSlot, imageRefsSlot(5, "Reference images (reference-to-video, capped at 10 s).")],
    aspect_ratios: [...AR_VIDEO_WAN],
    duration_range: { min: 2, max: 15 },
    default_duration: 5,
    max_count: 1,
    tags: ["audio", "character", "consistent", "sync", "sound"],
    higgsfield_ids: ["wan2_7"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/wan/v2.7/text-to-video",
        endpointByMode: { text: "fal-ai/wan/v2.7/text-to-video", image: "fal-ai/wan/v2.7/image-to-video", reference: "fal-ai/wan/v2.7/reference-to-video" },
        priority: 10,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "image_url", end_image: "end_image_url", image_references: "reference_image_urls[]" },
          params: { resolution: "resolution", seed: "seed" },
          byMode: {
            image: { aspect_ratio: null },
            reference: { duration: { field: "duration", format: "number", max: 10 } },
          },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.1, modifiers: [{ when: { resolution: "1080p" }, usd: 0.15 }], notes: "$0.10/s at 720p, $0.15/s at 1080p on every mode; edit: fal-ai/wan/v2.7/edit-video $0.10/s", source: `https://fal.ai/wan-2.7 (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Body: prompt, resolution, duration (number), plus aspect_ratio on text-to-video, image_url/end_image_url (no aspect_ratio) on image-to-video, or reference_image_urls + aspect_ratio on reference-to-video (duration capped at 10 s). negative_prompt and seed are pass-through extras outside the verified shape.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "wan/2-7-text-to-video",
        endpointByMode: { text: "wan/2-7-text-to-video", image: "wan/2-7-image-to-video", reference: "wan/2-7-r2v" },
        priority: 20,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: { field: "ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "first_frame_url", end_image: "last_frame_url", image_references: "reference_image[]" },
          params: { resolution: "resolution", seed: "seed" },
          byMode: {
            image: { aspect_ratio: null },
            reference: { aspect_ratio: { field: "aspect_ratio" }, duration: { field: "duration", format: "number", max: 10 } },
          },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.08, modifiers: [{ when: { resolution: "1080p" }, usd: 0.12 }], notes: "16 / 24 credits per second", source: `https://kie.ai/wan-2-7-video (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Three slugs with three field sets: wan/2-7-text-to-video takes the ratio as ratio, wan/2-7-r2v takes reference_image[] + aspect_ratio (duration capped at 10 s) and wan/2-7-image-to-video takes first_frame_url/last_frame_url without a ratio; resolution and duration (number) go everywhere. negative_prompt and seed are pass-through extras outside the verified shape. Video edit: wan/2-7-videoedit (not wired).`,
        verified: true,
      },
    ],
  },
  {
    id: "minimax_h3",
    name: "MiniMax H3",
    vendor: "MiniMax",
    description: "MiniMax H3 (Hailuo 03): open-weight 768P/2K video with native audio from text, first/last frame or image/video/audio references; 4-15 s.",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video", "reference-to-video"],
    parameters: [resolutionParam(["768P", "2K"], "768P"), seedParam, safetyParam, h3PromptExpansionParam],
    medias: [startImageSlot, endImageSlot, imageRefsSlot(9, "Reference images (Kie: first 5 free, then ~$0.045 each)."), videoRefsSlot(3), audioRefsSlot(3)],
    aspect_ratios: [...AR_VIDEO_WIDE],
    duration_range: { min: 4, max: 15 },
    default_duration: 6,
    max_count: 1,
    tags: ["open-weight", "audio", "reference", "start-frame", "end-frame", "2k"],
    higgsfield_ids: ["minimax_h3"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "minimax/h3/text-to-video",
        endpointByMode: { text: "minimax/h3/text-to-video", image: "minimax/h3/image-to-video", reference: "minimax/h3/reference-to-video" },
        priority: 10,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number", min: 5 },
          count: null,
          roles: { start_image: "image_url", end_image: "end_image_url", image_references: "reference_image_urls[]", video_references: "video_urls[]", audio_references: "audio_urls[]" },
          params: { resolution: "resolution", seed: "seed", enable_safety_checker: "enable_safety_checker", prompt_expansion_mode: "prompt_expansion_mode" },
          byMode: { image: { aspect_ratio: null } },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.06, modifiers: [{ when: { resolution: "2K" }, usd: 0.12 }], notes: "$0.06/s at 768P; fal quotes $0.06-0.16/s for 2K without an exact figure (budgeted here at $0.12); the pricing API bills minimax/h3/* per compute-second so treat both as indicative", source: `https://fal.ai/models/minimax/h3/text-to-video (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: false },
        notes: `${SHAPE_VERIFIED}. Owner prefix minimax/. Body: prompt, duration (number, at least 5 s on fal), resolution, plus aspect_ratio on text-to-video, image_url/end_image_url (no aspect_ratio) on image-to-video, or reference_image_urls + aspect_ratio on reference-to-video. seed, enable_safety_checker, prompt_expansion_mode and video_urls/audio_urls are outside the verified shape. H3 Max: minimax/h3-max/*.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "minimax-h3/text-to-video",
        endpointByMode: { text: "minimax-h3/text-to-video", image: "minimax-h3/image-to-video", reference: "minimax-h3/reference-to-video" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "first_frame_url", end_image: "last_frame_url", image_references: "reference_image_urls[]", video_references: "reference_video_urls[]", audio_references: "reference_audio_urls[]" },
          params: { resolution: "resolution", seed: omit("seed"), enable_safety_checker: omit("enable_safety_checker"), prompt_expansion_mode: omit("prompt_expansion_mode") },
          byMode: { image: { aspect_ratio: null } },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.04, modifiers: [{ when: { resolution: "2K" }, usd: 0.065 }], notes: "8 / 13 credits per second at 768P / 2K (an earlier Kie copy listed 18 / 29); video references billed on input + output seconds; first 5 images free then 9 credits each", source: `https://kie.ai/minimax-h3 (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Body: prompt, duration (number), resolution 768P|2K, plus aspect_ratio on text-to-video (adaptive rejected there), first_frame_url/last_frame_url (no aspect_ratio) on image-to-video, or reference_image_urls + aspect_ratio on reference-to-video. Wire fields are snake_case; reference_video_urls/reference_audio_urls are outside the verified shape.`,
        verified: true,
      },
    ],
  },
  {
    id: "hailuo_2_3",
    name: "Hailuo 2.3 Pro",
    vendor: "MiniMax",
    description: "MiniMax Hailuo 2.3 Pro: physics-accurate, emotionally expressive image-to-video (6 / 10 s on Kie; a fixed 6 s at 1080p on fal). Needs a start frame.",
    output_type: "video",
    capabilities: ["image-to-video"],
    parameters: [resolutionParam(["768P", "1080P"], "768P", "Output resolution (Kie only; fal's pro endpoint is fixed at 1080p)."), promptOptimizerParam],
    medias: [{ ...startImageSlot, required: true, description: "Start frame to animate (required)." }],
    aspect_ratios: [],
    durations: [6, 10],
    default_duration: 6,
    max_count: 1,
    tags: ["physics", "emotion", "facial", "realistic", "1080p", "natural"],
    higgsfield_ids: ["minimax_hailuo"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/minimax/hailuo-2.3/pro/image-to-video",
        fixedDuration: 6,
        pinnedParams: { resolution: "1080P" },
        priority: 10,
        input: {
          aspect_ratio: null,
          duration: null,
          count: null,
          roles: { start_image: "image_url" },
          params: { resolution: omit("resolution"), prompt_optimizer: "prompt_optimizer" },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: { unit: "generation", usd: 0.49, notes: "pro: $0.49 per 6 s clip at 1080p (no duration choice); standard tier fal-ai/minimax/hailuo-2.3/standard/image-to-video $0.28 (6 s) / $0.56 (10 s) at 768P", source: `https://fal.ai/models/fal-ai/minimax/hailuo-2.3/pro/image-to-video (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Body: prompt, image_url, prompt_optimizer. The pro endpoint has no duration or resolution field (always 6 s / 1080p); only the standard tier takes duration '6' | '10'. Text-to-video, end frames and the standard tier are not wired (the model requires a start frame). Superseded by MiniMax H3.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "hailuo/2-3-image-to-video-pro",
        priority: 20,
        input: {
          aspect_ratio: null,
          duration: { field: "duration", format: "string" },
          count: null,
          roles: { start_image: "image_url" },
          params: { resolution: "resolution", prompt_optimizer: omit("prompt_optimizer") },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.04, modifiers: [{ when: { resolution: "768P", duration: 10 }, usd: 0.045 }, { when: { resolution: "1080P" }, usd: 0.065 }], notes: "per clip: 6 s 768P $0.22, 10 s 768P $0.45, 6 s 1080P $0.39 (no 10 s at 1080P); standard slug hailuo/2-3-image-to-video-standard $0.15 / $0.26 / $0.26", source: `https://kie.ai/hailuo-2-3 (${PRICES_CHECKED})`, verified_at: CHECKED_AT, verified: true },
        notes: `${SHAPE_VERIFIED}. Body: prompt, image_url, duration '6' | '10', resolution 768P|1080P. Kie has no Hailuo 2.3 text-to-video and no end frame; prompt_optimizer is fal-only.`,
        verified: true,
      },
    ],
  },
  {
    id: "grok_video",
    name: "Grok Imagine Video",
    vendor: "xAI",
    description: "xAI Grok Imagine video (1.5 on fal): budget text/image-to-video with audio at 480p/720p/1080p; 6-15 s.",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video"],
    parameters: [resolutionParam(["480p", "720p", "1080p"], "720p"), grokModeParam],
    medias: [startImageSlot],
    aspect_ratios: [...AR_GROK],
    duration_range: { min: 6, max: 15 },
    default_duration: 6,
    max_count: 1,
    tags: ["audio", "versatile", "start-frame", "budget"],
    higgsfield_ids: ["grok_video", "grok_video_v15"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "xai/grok-imagine-video/v1.5/text-to-video",
        endpointByMode: { text: "xai/grok-imagine-video/v1.5/text-to-video", image: "xai/grok-imagine-video/v1.5/image-to-video" },
        priority: 10,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "image_url" },
          params: { resolution: "resolution", mode: omit("mode") },
          byMode: { image: { aspect_ratio: null } },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.14,
          modifiers: [
            { when: { resolution: "480p" }, usd: 0.08 },
            { when: { resolution: "1080p" }, usd: 0.25 },
          ],
          notes: "v1.5 endpoints: $0.08 / $0.14 / $0.25 per second at 480p / 720p / 1080p, 1-15 s; the unversioned xai/grok-imagine-video/* endpoints bill $0.05 / $0.07 per second",
          source: `https://fal.ai/models/xai/grok-imagine-video/v1.5/image-to-video (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Owner prefix xai/. Body: prompt, duration (number), resolution, plus aspect_ratio on text-to-video or image_url (no aspect_ratio) on image-to-video. Reference-to-video for Grok is not wired, so image references are not offered.`,
        verified: true,
      },
      {
        provider: "kie",
        endpoint: "grok-imagine/text-to-video",
        endpointByMode: { text: "grok-imagine/text-to-video", image: "grok-imagine/image-to-video" },
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "image_urls[]" },
          params: { resolution: "resolution", mode: "mode" },
          byMode: { image: { duration: { field: "duration", format: "string" } } },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.0225,
          modifiers: [
            { when: { resolution: "480p" }, usd: 0.012 },
            { when: { resolution: "1080p" }, usd: 0.04 },
          ],
          notes: "2.4 / 4.5 / 8 credits per second at 480p / 720p / 1080p; audio always on",
          source: `https://kie.ai/grok-imagine (${PRICES_CHECKED})`,
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: `${SHAPE_VERIFIED}. Body: prompt, aspect_ratio (2:3, 3:2, 1:1, 16:9, 9:16), mode normal, resolution, duration (a number on text-to-video, a string on image-to-video, at least 6 s); image-to-video takes image_urls [first]. Kie allows up to 30 s and nsfw_checker. Extend: grok-imagine/extend, upscale: grok-imagine/upscale (Kie tasks only).`,
        verified: true,
      },
    ],
  },
  {
    id: "gemini_omni_flash_1_1",
    name: "Gemini Omni Flash 1.1",
    vendor: "Google",
    description: "Google Gemini Omni Flash 1.1: natural-language video generation and editing with audio from text, first/last frame or image + video references; 360p-4K, 4-10 s.",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video", "first-last-frame-to-video", "reference-to-video", "video-edit"],
    parameters: [resolutionParam(["360p", "720p", "1080p", "4k"], "720p"), seedParam],
    medias: [startImageSlot, endImageSlot, imageRefsSlot(7, "Reference images (Kie allows up to 7 quota units; fal up to 10)."), videoRefsSlot(1, "One reference video (fal reference-to-video).")],
    aspect_ratios: [...AR_VIDEO_VEO],
    durations: [4, 6, 8, 10],
    default_duration: 8,
    max_count: 1,
    tags: ["audio", "reference", "video-edit", "natural-language", "4k"],
    higgsfield_ids: ["gemini_omni_flash_1_1", "gemini_omni"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "google/gemini-omni-flash/v1.1/text-to-video",
        endpointByMode: { text: "google/gemini-omni-flash/v1.1/text-to-video", image: "google/gemini-omni-flash/v1.1/image-to-video", reference: "google/gemini-omni-flash/v1.1/reference-to-video" },
        priority: 10,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "image_url", end_image: "end_image_url", image_references: "image_urls[]", video_references: "reference_video_urls[]" },
          params: { resolution: "resolution", seed: omit("seed") },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: {
          unit: "second",
          usd: 0.1,
          modifiers: [
            { when: { resolution: "360p" }, usd: 0.03 },
            { when: { resolution: "1080p" }, usd: 0.15 },
            { when: { resolution: "4k" }, usd: 0.3 },
          ],
          notes: "v1.1 endpoints bill per output second by resolution; the older google/gemini-omni-flash* endpoints are token-billed",
          source: "https://fal.ai/models/google/gemini-omni-flash/v1.1/image-to-video",
          verified_at: CHECKED_AT,
          verified: true,
        },
        notes: "Fields audited against fal's schema (2026-09-02): t2v prompt/aspect_ratio/resolution/duration; i2v image_url + end_image_url; r2v image_urls + reference_video_urls. Video editing: google/gemini-omni-flash/v1.1/edit (prompt + video_url, not wired).",
        verified: false,
      },
      {
        provider: "kie",
        endpoint: "google/gemini-omni-flash-1-1",
        priority: 20,
        input: {
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "string" },
          count: null,
          roles: { start_image: "first_frame_url", end_image: "last_frame_url", image_references: "image_urls[]" },
          params: { resolution: "resolution", seed: "seed" },
          strictParams: true,
        },
        output: KIE_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.079, notes: "derived from $0.315 per 4 s at 720p; up to $1.05 for 10 s at 4K; with a video input $0.84 flat (720p/1080p) or $1.26 (4K)", source: "https://docs.kie.ai/market/google/gemini-omni-flash-1-1 (gap-mapping report)", verified_at: CHECKED_AT, verified: false },
        notes: "Duration is a string ('4' | '6' | '8' | '10'). Video references use a `video_list` of trimmed-video objects plus audio_ids / character_ids (Omni character & voice registry) - not wired.",
        verified: false,
      },
    ],
  },
  {
    id: "ltx_2",
    name: "LTX-2.3",
    vendor: "Lightricks",
    description: "LTX-2.3: open-weight budget text/image-to-video with audio at 1080p+ (6-10 s); the cheapest per-second option on fal.",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video"],
    parameters: [resolutionParam(["1080p", "1440p", "2160p"], "1080p"), generateAudioParam(true)],
    medias: [startImageSlot],
    aspect_ratios: [...AR_VIDEO_COMMON],
    durations: [6, 8, 10],
    default_duration: 8,
    max_count: 1,
    tags: ["open-weights", "budget", "fast", "audio"],
    status: "active",
    bindings: [
      {
        provider: "fal",
        endpoint: "fal-ai/ltx-2.3/text-to-video",
        endpointByMode: { text: "fal-ai/ltx-2.3/text-to-video", image: "fal-ai/ltx-2.3/image-to-video" },
        priority: 10,
        input: {
          negative_prompt: "negative_prompt",
          aspect_ratio: { field: "aspect_ratio" },
          duration: { field: "duration", format: "number" },
          count: null,
          roles: { start_image: "image_url" },
          params: { resolution: "resolution", generate_audio: "generate_audio" },
          strictParams: true,
        },
        output: FAL_VIDEO_OUTPUT,
        pricing: { unit: "second", usd: 0.08, notes: "text-to-video $0.08/s, image-to-video $0.06/s; /fast variants $0.04/s at 1080p; quality tier per megapixel", source: "https://fal.ai/models/fal-ai/ltx-2.3/text-to-video", verified_at: CHECKED_AT, verified: false },
        notes: "fal only (no LTX on Kie). The plain fal-ai/ltx-2/* ids are absent from the Sep-2026 registry, so the 2.3 ids are bound; fal-ai/ltx-2.3/*/fast are the cheaper siblings. Field names follow the LTX-2 schema (image_url, duration, resolution, aspect_ratio, generate_audio) - verify.",
        verified: false,
      },
    ],
  },
  {
    id: "kling_2_5_turbo_pro_api",
    name: "Kling 2.5 Turbo Pro (Higgsfield API)",
    vendor: "Kling",
    description: "Kling 2.5 Turbo Pro text-to-video or image-to-video through Higgsfield API.",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video"],
    parameters: [cfgScaleParam],
    medias: [startImageSlot],
    aspect_ratios: [],
    durations: [5, 10],
    default_duration: 5,
    max_count: 1,
    tags: ["kling", "motion", "pro"],
    status: "beta",
    bindings: [{
      provider: "higgsfield",
      endpoint: "kling-video/v2.5-turbo/pro/text-to-video",
      endpointByMode: { image: "kling-video/v2.5-turbo/pro/image-to-video" },
      supportedModes: ["text", "image"],
      input: { aspect_ratio: null, negative_prompt: "negative_prompt", duration: { field: "duration" }, count: null, roles: { start_image: "image_url" }, params: { cfg_scale: "cfg_scale" }, strictParams: true },
      output: { outputs: [{ path: "video", kind: "video" }] },
      notes: "Both endpoints and request schemas appear in Higgsfield's public OpenAPI subset. Account quote and live result pending.",
      verified: false,
    }],
  },
  {
    id: "kling_2_5_turbo_standard_api",
    name: "Kling 2.5 Turbo Standard (Higgsfield API)",
    vendor: "Kling",
    description: "Kling 2.5 Turbo Standard image-to-video through Higgsfield API.",
    output_type: "video",
    capabilities: ["image-to-video"],
    parameters: [cfgScaleParam],
    medias: [{ ...startImageSlot, required: true }],
    aspect_ratios: [],
    durations: [5, 10],
    default_duration: 5,
    max_count: 1,
    tags: ["kling", "motion", "standard"],
    status: "beta",
    bindings: [{
      provider: "higgsfield",
      endpoint: "kling-video/v2.5-turbo/standard/image-to-video",
      supportedModes: ["image"],
      input: { aspect_ratio: null, negative_prompt: "negative_prompt", duration: { field: "duration" }, count: null, roles: { start_image: "image_url" }, params: { cfg_scale: "cfg_scale" }, strictParams: true },
      output: { outputs: [{ path: "video", kind: "video" }] },
      notes: "Endpoint and request schema appear in Higgsfield's public OpenAPI subset. Account quote and live result pending.",
      verified: false,
    }],
  },
  {
    id: "hailuo_2_3_standard_api",
    name: "Hailuo 2.3 Standard (Higgsfield API)",
    vendor: "MiniMax",
    description: "Hailuo 2.3 Standard text-to-video or image-to-video through Higgsfield API.",
    output_type: "video",
    capabilities: ["text-to-video", "image-to-video"],
    parameters: [promptOptimizerParam],
    medias: [startImageSlot],
    aspect_ratios: [],
    durations: [6, 10],
    default_duration: 6,
    max_count: 1,
    tags: ["hailuo", "motion", "standard"],
    status: "beta",
    bindings: [{
      provider: "higgsfield",
      endpoint: "minimax/hailuo-2.3/standard/text-to-video",
      endpointByMode: { image: "minimax/hailuo-2.3/standard/image-to-video" },
      supportedModes: ["text", "image"],
      input: { aspect_ratio: null, duration: { field: "duration" }, count: null, roles: { start_image: "image_url" }, params: { prompt_optimizer: "prompt_optimizer" }, strictParams: true },
      output: { outputs: [{ path: "video", kind: "video" }] },
      notes: "Both endpoints and request schemas appear in Higgsfield's public OpenAPI subset. Account quote and live result pending.",
      verified: false,
    }],
  },
];
